package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gorilla/mux"

	"trading-backend/internal/staticdata"
)

func resolveExpiredAlerts() {
	result, err := db.Exec(`
		UPDATE alerts
		SET is_active = 0,
		    resolved_at = CURRENT_TIMESTAMP,
		    resolved_reason = 'EXPIRED',
		    resolved_note = 'Signal expired without user action'
		WHERE is_active = 1
		  AND expiry_date IS NOT NULL
		  AND UPPER(TRIM(alert_type)) != 'SELL'
		  AND datetime(expiry_date) < datetime('now')
	`)
	if err != nil {
		log.Printf("[ALPHA EDGE] Failed to resolve expired alerts: %v", err)
		return
	}
	if rows, err := result.RowsAffected(); err == nil && rows > 0 {
		if _, actionErr := db.Exec(`
				UPDATE security_actions
			SET status = 'EXPIRED', updated_at = CURRENT_TIMESTAMP
			WHERE alert_id IN (
				SELECT id FROM alerts WHERE resolved_reason = 'EXPIRED'
			)
			  AND status IN ('OPEN', 'BLOCKED')
			`); actionErr != nil && !securityActionTableMissing(actionErr) {
			log.Printf("[SECURITY ACTIONS] Failed to expire action queue entries: %v", actionErr)
		}
		log.Printf("[ALPHA EDGE] Resolved %d expired alerts", rows)
	}
}

func getAlerts(w http.ResponseWriter, r *http.Request) {
	resolveExpiredAlerts()

	// Check if includeHistory query parameter is set
	includeHistory := r.URL.Query().Get("includeHistory") == "true"

	var rows *sql.Rows
	var err error

	if includeHistory {
		// For history view: Return ALL alerts regardless of status or expiry
		rows, err = db.Query(`
			SELECT a.id, a.ticker, a.alert_type, a.strength, a.expiry_date, a.exchange_prefix, a.timeframe, a.source, a.affected_positions, a.alert_price, a.resolved_reason, a.resolved_note, a.created_at, a.is_active
			FROM alerts a
			ORDER BY a.created_at DESC
		`)
	} else {
		// For the live alert stack: return active alerts that have not expired.
		// Do not hide TradingView events based on our app-side position state.
		// State context belongs in the UI; silently filtering here makes real alerts disappear.
		rows, err = db.Query(`
			SELECT a.id, a.ticker, a.alert_type, a.strength, a.expiry_date, a.exchange_prefix, a.timeframe, a.source, a.affected_positions, a.alert_price, a.resolved_reason, a.resolved_note, a.created_at, a.is_active
			FROM alerts a
			WHERE a.is_active = 1
			AND (
				a.expiry_date IS NULL
				OR datetime(a.expiry_date) >= datetime('now')
			)
			ORDER BY a.created_at DESC
		`)
	}
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	alerts := []Alert{}
	for rows.Next() {
		var a Alert
		var ticker, alertType, strength, exchangePrefix sql.NullString
		var expiryDate sql.NullTime
		var timeframe, source, affectedPositions, resolvedReason, resolvedNote sql.NullString
		var alertPrice sql.NullFloat64
		err := rows.Scan(&a.ID, &ticker, &alertType, &strength, &expiryDate, &exchangePrefix, &timeframe, &source, &affectedPositions, &alertPrice, &resolvedReason, &resolvedNote, &a.CreatedAt, &a.IsActive)
		if err != nil {
			log.Printf("[ALPHA EDGE] Failed to scan alert row: %v", err)
			continue
		}
		if ticker.Valid {
			a.Ticker = ticker.String
		}
		if alertType.Valid {
			a.AlertType = alertType.String
		}
		if strength.Valid {
			a.Strength = strength.String
		}
		if expiryDate.Valid {
			value := expiryDate.Time
			a.ExpiryDate = &value
		}
		if exchangePrefix.Valid {
			a.ExchangePrefix = exchangePrefix.String
		}
		a.AlertType = canonicalAlertType(a.AlertType)
		if timeframe.Valid {
			a.Timeframe = timeframe.String
		}
		if source.Valid {
			a.Source = source.String
		}
		if affectedPositions.Valid {
			a.AffectedPositions = affectedPositions.String
		}
		if alertPrice.Valid && alertPrice.Float64 > 0 {
			a.AlertPrice = floatPtr(alertPrice.Float64)
		}
		if resolvedReason.Valid {
			a.ResolvedReason = resolvedReason.String
		}
		if resolvedNote.Valid {
			a.ResolvedNote = resolvedNote.String
		}
		alerts = append(alerts, a)
	}
	rows.Close()

	for i := range alerts {
		attachAlertPriceContext(&alerts[i])
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(alerts)
}

func createAlert(w http.ResponseWriter, r *http.Request) {
	var alert Alert
	if err := json.NewDecoder(r.Body).Decode(&alert); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	alert.AlertType = canonicalAlertType(alert.AlertType)
	if strings.HasPrefix(alert.AlertType, "WEIGHT_") {
		http.Error(w, "Weight reviews are generated by the policy, not manual signals", 400)
		return
	}
	alert.AlertPrice = lookupCurrentMarketPrice(alert.Ticker, alert.ExchangePrefix)

	result, err := db.Exec(`
		INSERT INTO alerts (ticker, alert_type, strength, expiry_date, alert_price)
		VALUES (?, ?, ?, ?, ?)
	`, alert.Ticker, alert.AlertType, alert.Strength, alert.ExpiryDate, nullableFloat(alert.AlertPrice))

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	id, _ := result.LastInsertId()
	alert.ID = int(id)
	alert.CreatedAt = time.Now()
	alert.IsActive = true
	if err := ensureSecurityActionForAlertID(alert.ID); err != nil {
		log.Printf("[SECURITY ACTIONS] Failed to project manual alert %d: %v", alert.ID, err)
	}

	select {
	case alertChannel <- alert:
		log.Printf("[ALPHA EDGE] New alert broadcasted: %s %s", alert.Ticker, alert.AlertType)
	default:
		log.Println("[ALPHA EDGE] Alert channel full, skipping broadcast")
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(alert)
}

func dismissAlert(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	id := vars["id"]
	alertID, parseErr := strconv.Atoi(id)
	if parseErr != nil || alertID < 1 {
		http.Error(w, "Invalid alert id", http.StatusBadRequest)
		return
	}
	if err := ensureSecurityActionForAlertID(alertID); err != nil && err != sql.ErrNoRows {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if isExit, err := activeExitActionForAlert(alertID); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	} else if isExit {
		http.Error(w, "Exit actions require execution or an explicit override", http.StatusConflict)
		return
	}

	_, err := db.Exec(`
		UPDATE alerts
		SET is_active = 0,
		    resolved_at = COALESCE(resolved_at, CURRENT_TIMESTAMP),
		    resolved_reason = COALESCE(resolved_reason, 'DISMISSED'),
		    resolved_note = COALESCE(resolved_note, 'Alert dismissed without recording a decision')
		WHERE id = ?
	`, id)

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	log.Printf("[ALPHA EDGE] Alert %s dismissed", id)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": "dismissed"})
}

func streamAlerts(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	// CORS is handled by corsMiddleware (origin allowlist); no wildcard here.

	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "Streaming not supported", http.StatusInternalServerError)
		return
	}

	log.Println("[ALPHA EDGE] New SSE client connected")

	// Send initial connection message
	fmt.Fprintf(w, "data: {\"type\":\"connected\"}\n\n")
	flusher.Flush()

	// Listen for new alerts
	sessionCheck := time.NewTicker(15 * time.Second)
	defer sessionCheck.Stop()
	for {
		select {
		case alert := <-alertChannel:
			if ownerAccess.enabled && accessCookie(r, "session") != "" {
				if scope, _, err := ownerSession(r); err != nil || scope != "owner" {
					return
				}
			}
			data, _ := json.Marshal(alert)
			fmt.Fprintf(w, "data: %s\n\n", data)
			flusher.Flush()
		case <-sessionCheck.C:
			if ownerAccess.enabled && accessCookie(r, "session") != "" {
				if scope, _, err := ownerSession(r); err != nil || scope != "owner" {
					return
				}
			}
			fmt.Fprint(w, ": heartbeat\n\n")
			flusher.Flush()
		case <-r.Context().Done():
			log.Println("[ALPHA EDGE] SSE client disconnected")
			return
		}
	}
}

// DEPRECATED: getSecurities - use statement_holdings via /api/statements endpoints
// DEPRECATED: updateSecurity - use statement_holdings via /api/statements endpoints

func getDecisions(w http.ResponseWriter, r *http.Request) {
	limit := 500
	if raw := strings.TrimSpace(r.URL.Query().Get("limit")); raw != "" {
		if parsed, err := strconv.Atoi(raw); err == nil {
			limit = parsed
		}
	}
	if limit < 50 {
		limit = 50
	}
	if limit > 2000 {
		limit = 2000
	}

	rows, err := db.Query(`
		SELECT d.id, d.alert_id, d.decision, d.notes, d.position_pct_after, d.created_at,
		       a.ticker, a.alert_type
		FROM decisions d
		LEFT JOIN alerts a ON d.alert_id = a.id
		ORDER BY d.created_at DESC
		LIMIT ?
	`, limit)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	// Initialize with empty slice to ensure JSON returns [] not null
	decisions := make([]map[string]interface{}, 0)
	for rows.Next() {
		var id int
		var alertID sql.NullInt64
		var decision string
		var notes sql.NullString
		var positionPct *float64
		var createdAt string
		var ticker sql.NullString
		var alertType sql.NullString

		err := rows.Scan(&id, &alertID, &decision, &notes, &positionPct, &createdAt, &ticker, &alertType)
		if err != nil {
			log.Printf("[DECISIONS] Scan error: %v", err)
			continue
		}

		decisionMap := map[string]interface{}{
			"id":                 id,
			"alert_id":           nil,
			"decision":           decision,
			"notes":              "",
			"position_pct_after": positionPct,
			"created_at":         createdAt,
			"ticker":             "",
			"alert_type":         "",
		}
		if alertID.Valid {
			decisionMap["alert_id"] = alertID.Int64
		}
		if notes.Valid {
			decisionMap["notes"] = notes.String
		}
		if ticker.Valid {
			decisionMap["ticker"] = ticker.String
		}
		if alertType.Valid {
			decisionMap["alert_type"] = alertType.String
		}

		decisions = append(decisions, decisionMap)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(decisions)
}

func createDecision(w http.ResponseWriter, r *http.Request) {
	var decision Decision
	if err := json.NewDecoder(r.Body).Decode(&decision); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if decision.Units != nil && (!finitePositive(*decision.Units) || decision.AlertID == nil || strings.EqualFold(decision.Decision, "IGNORE")) {
		http.Error(w, "Units must be positive and belong to a security execution", http.StatusBadRequest)
		return
	}

	var ticker string
	var alertType string
	var alertSource string

	// For rebalance dismissals or other decisions without an alert, skip alert lookup
	if decision.AlertID != nil {
		// Get alert details to extract ticker
		err := db.QueryRow(`
			SELECT ticker, alert_type, COALESCE(source,'') FROM alerts WHERE id = ?
		`, *decision.AlertID).Scan(&ticker, &alertType, &alertSource)

		if err != nil {
			http.Error(w, "Alert not found", http.StatusNotFound)
			return
		}
		if projectionErr := ensureSecurityActionForAlertID(*decision.AlertID); projectionErr != nil {
			http.Error(w, projectionErr.Error(), http.StatusInternalServerError)
			return
		}
		// The Alert Stack and Positions must use the same cash check and atomic
		// execution write. Do not resolve a buy before validating its funding.
		if strings.HasPrefix(alertType, "WEIGHT_") && strings.EqualFold(strings.TrimSpace(decision.Decision), "IGNORE") {
			var actionID int
			if err := db.QueryRow(`SELECT id FROM security_actions WHERE alert_id=?`, *decision.AlertID).Scan(&actionID); err != nil {
				http.Error(w, err.Error(), 500)
				return
			}
			ignoreSecurityAction(w, mux.SetURLVars(r, map[string]string{"id": strconv.Itoa(actionID)}))
			return
		}
		if spec, ok := securityActionSpecForAlert(alertType, alertSource); ok && (spec.Intent == "DEPLOY" || strings.HasPrefix(alertType, "WEIGHT_")) &&
			!strings.EqualFold(strings.TrimSpace(decision.Decision), "IGNORE") {
			var actionID int
			if err := db.QueryRow(`SELECT id FROM security_actions WHERE alert_id = ?`, *decision.AlertID).Scan(&actionID); err != nil {
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			request := securityExecutionRequest{Units: decision.Units}
			if decision.Notes != nil {
				request.Notes = *decision.Notes
			}
			r = mux.SetURLVars(r, map[string]string{"id": strconv.Itoa(actionID)})
			recordSecurityActionExecutionRequest(w, r, request)
			return
		}
		if decision.Units != nil {
			var scope string
			if err := db.QueryRow(`SELECT scope FROM security_actions WHERE alert_id = ?`, *decision.AlertID).Scan(&scope); err != nil || scope != "SECURITY" {
				http.Error(w, "Units require a single-security action", http.StatusBadRequest)
				return
			}
		}
		if strings.EqualFold(strings.TrimSpace(decision.Decision), "IGNORE") {
			isExit, actionErr := activeExitActionForAlert(*decision.AlertID)
			if actionErr != nil {
				http.Error(w, actionErr.Error(), http.StatusInternalServerError)
				return
			}
			if isExit {
				http.Error(w, "Exit actions require execution or an explicit override", http.StatusConflict)
				return
			}
		}
	}

	result, err := db.Exec(`
		INSERT INTO decisions (alert_id, decision, notes, position_pct_after)
		VALUES (?, ?, ?, ?)
	`, decision.AlertID, decision.Decision, decision.Notes, decision.PositionPctAfter)

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Mark alert as resolved (only if alert_id is provided)
	if decision.AlertID != nil {
		if _, execErr := db.Exec(`
			UPDATE alerts
			SET is_active = 0,
			    resolved_at = CURRENT_TIMESTAMP,
			    resolved_reason = ?,
			    resolved_note = 'User decision recorded'
			WHERE id = ?
		`, decision.Decision, *decision.AlertID); execErr != nil {
			// Decision is already recorded; do not 500 (a retry would
			// duplicate it). But the alert staying active must not be silent.
			log.Printf("[ALERTS ERROR] Decision recorded but failed to resolve alert %d: %v", *decision.AlertID, execErr)
		}
		if actionErr := syncLegacyDecisionIntoSecurityAction(*decision.AlertID, decision.Decision, decision.Notes, decision.Units); actionErr != nil {
			log.Printf("[SECURITY ACTIONS] Decision recorded but failed to update action queue for alert %d: %v", *decision.AlertID, actionErr)
		}
	}

	// If a state-change alert is ignored, restore the prior state instead of leaving the
	// webhook-applied state in place. "Ignore" should mean "keep what I had", not "hide it
	// while leaving me stuck in the new state".
	if decision.AlertID != nil && decision.Decision == "IGNORE" {
		switch alertType {
		case "SELL", "SELL_50":
			_, err := db.Exec(`
				INSERT INTO security_positions (ticker, position_state, stopped_waiting_reentry, last_updated)
				VALUES (?, 'BUY', 0, CURRENT_TIMESTAMP)
				ON CONFLICT(ticker) DO UPDATE SET
					position_state = 'BUY',
					stopped_waiting_reentry = 0,
					last_updated = CURRENT_TIMESTAMP
			`, ticker)
			if err != nil {
				log.Printf("[ALPHA EDGE] Failed to restore BUY state after ignoring %s for %s: %v", alertType, ticker, err)
			} else {
				log.Printf("[ALPHA EDGE] IGNORE restored %s -> BUY (source: %s)", ticker, alertSource)
			}
		case "BUY", "BREAKOUT":
			_, err := db.Exec(`
				INSERT INTO security_positions (ticker, position_state, stopped_waiting_reentry, last_updated)
				VALUES (?, 'SELL', 0, CURRENT_TIMESTAMP)
				ON CONFLICT(ticker) DO UPDATE SET
					position_state = 'SELL',
					stopped_waiting_reentry = 0,
					last_updated = CURRENT_TIMESTAMP
			`, ticker)
			if err != nil {
				log.Printf("[ALPHA EDGE] Failed to restore SELL state after ignoring %s for %s: %v", alertType, ticker, err)
			} else {
				log.Printf("[ALPHA EDGE] IGNORE restored %s -> SELL (source: %s)", ticker, alertSource)
			}
		case "REENTRY":
			_, err := db.Exec(`
				INSERT INTO security_positions (ticker, position_state, stopped_waiting_reentry, last_updated)
				VALUES (?, 'SELL', 1, CURRENT_TIMESTAMP)
				ON CONFLICT(ticker) DO UPDATE SET
					position_state = 'SELL',
					stopped_waiting_reentry = 1,
					last_updated = CURRENT_TIMESTAMP
			`, ticker)
			if err != nil {
				log.Printf("[ALPHA EDGE] Failed to keep %s in SELL waiting state after ignoring REENTRY: %v", ticker, err)
			} else {
				log.Printf("[ALPHA EDGE] IGNORE kept %s in SELL waiting state after REENTRY", ticker)
			}
		}
	}

	// If decision is BUY or SELL (not IGNORE), update security position
	if decision.AlertID != nil && (decision.Decision == "BUY" || decision.Decision == "SELL" || decision.Decision == "SELL_50") {
		positionState := decision.Decision
		if decision.Decision == "SELL_50" {
			positionState = "SELL"
		}
		_, err := db.Exec(`
			INSERT INTO security_positions (ticker, position_state, last_updated)
			VALUES (?, ?, CURRENT_TIMESTAMP)
			ON CONFLICT(ticker) DO UPDATE SET
				position_state = excluded.position_state,
				last_updated = CURRENT_TIMESTAMP
		`, ticker, positionState)

		if err != nil {
			log.Printf("[ALPHA EDGE] Failed to update position for %s: %v", ticker, err)
		} else {
			log.Printf("[ALPHA EDGE] Updated position: %s -> %s", ticker, decision.Decision)
		}
	}

	syncManagedETFTacticalState(ticker)
	id, _ := result.LastInsertId()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"id":      id,
		"message": "Decision recorded",
	})
}

// DEPRECATED: createHolding - use /api/statements/import for bulk statement imports

func getPortfolio(w http.ResponseWriter, r *http.Request) {
	// Get latest statement
	var statement AccountStatement
	err := db.QueryRow(`
		SELECT id, account_name, statement_date, total_value_aud, cash_aud,
		       usd_value, usd_aud, gbp_value, gbp_aud, aud_value, created_at
		FROM account_statements
		ORDER BY statement_date DESC
		LIMIT 1
	`).Scan(&statement.ID, &statement.AccountName, &statement.StatementDate,
		&statement.TotalValueAUD, &statement.CashAUD, &statement.USDValue, &statement.USDAUD,
		&statement.GBPValue, &statement.GBPAUD, &statement.AUDValue, &statement.CreatedAt)

	if err == sql.ErrNoRows {
		// No data yet - return empty portfolio for health check
		log.Println("[ALPHA EDGE] No account statements found, returning empty portfolio")
		portfolio := map[string]interface{}{
			"total_value":         0.0,
			"cash_on_hand":        0.0,
			"exposure":            0.0,
			"profit_loss":         0.0,
			"profit_loss_percent": 0.0,
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(portfolio)
		return
	}

	if err != nil {
		log.Printf("[ALPHA EDGE] Error fetching latest statement for portfolio: %v", err)
		http.Error(w, "Error fetching portfolio", http.StatusInternalServerError)
		return
	}

	// Calculate total holdings value and P/L from holdings
	// Cash-equivalent ETFs are excluded from equity exposure and added to cash_on_hand.
	var totalHoldingsValue float64
	var totalGainLoss float64
	var totalCost float64
	var cashEquivalentValue float64

	cashTickerKey := stockAnalysisTickerKeySQL("COALESCE(m.ticker, h.ticker, '')")
	err = db.QueryRow(fmt.Sprintf(`
		SELECT
			COALESCE(SUM(CASE WHEN %s NOT IN ('BSUB', 'AAA') THEN h.value_aud ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN %s NOT IN ('BSUB', 'AAA') THEN h.gain_loss_aud ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN %s NOT IN ('BSUB', 'AAA') THEN h.cost_aud ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN %s IN ('BSUB', 'AAA') THEN h.value_aud ELSE 0 END), 0)
		FROM statement_holdings h
		LEFT JOIN company_mappings m ON h.details = m.company_name
		WHERE h.statement_id = ?
	`, cashTickerKey, cashTickerKey, cashTickerKey, cashTickerKey), statement.ID).Scan(&totalHoldingsValue, &totalGainLoss, &totalCost, &cashEquivalentValue)

	if err != nil {
		log.Printf("[ALPHA EDGE] Error calculating portfolio stats: %v", err)
		// Fallback to statement values if holdings query fails
		totalHoldingsValue = statement.TotalValueAUD - statement.CashAUD
		totalGainLoss = 0
		totalCost = totalHoldingsValue
		cashEquivalentValue = 0
	}

	// Calculate exposure percentage (cash equivalents count as cash, not equity exposure)
	exposure := 0.0
	if statement.TotalValueAUD > 0 {
		exposure = (totalHoldingsValue / statement.TotalValueAUD) * 100
	}

	// Calculate profit/loss percentage
	profitLossPercent := 0.0
	if totalCost > 0 {
		profitLossPercent = (totalGainLoss / totalCost) * 100
	}

	portfolio := map[string]interface{}{
		"total_value":         statement.TotalValueAUD,
		"cash_on_hand":        statement.CashAUD + cashEquivalentValue,
		"exposure":            exposure,
		"profit_loss":         totalGainLoss,
		"profit_loss_percent": profitLossPercent,
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(portfolio)
}

// Calculate expiry date (3 trading days from now, skipping weekends, in Sydney time)
func calculateExpiryDate(from time.Time) time.Time {
	loc, err := time.LoadLocation("Australia/Sydney")
	if err != nil {
		loc = from.Location()
	}

	// Work in Sydney time so "end of day" aligns with the user's trading day
	current := from.In(loc)
	tradingDaysRemaining := 3

	for tradingDaysRemaining > 0 {
		current = current.Add(24 * time.Hour)
		// Skip weekends (Saturday = 6, Sunday = 0)
		if current.Weekday() != time.Saturday && current.Weekday() != time.Sunday {
			tradingDaysRemaining--
		}
	}

	// Set to end of day (23:59:59) in Sydney time
	return time.Date(current.Year(), current.Month(), current.Day(), 23, 59, 59, 0, loc)
}

func normalizeAlertScript(script string) string {
	switch strings.ToLower(strings.TrimSpace(script)) {
	case "oms", "cdf":
		return "cdf"
	case "atr_oscillator", "tms":
		return "tms"
	case "etf_oms", "etf_cdf", "etf_tms":
		return "etf_tms"
	case "regime", "regime_equities", "q4d":
		return "q4d"
	case "regime_commodities", "ctf":
		return "ctf"
	case "regime_position_sizing", "q3d":
		return "q3d"
	default:
		return strings.ToLower(strings.TrimSpace(script))
	}
}

func canonicalAlertType(alertType string) string {
	normalized := strings.ToUpper(strings.TrimSpace(alertType))
	normalized = strings.ReplaceAll(normalized, "-", "_")
	normalized = strings.ReplaceAll(normalized, " ", "_")

	switch normalized {
	case "SELL_HALF", "SELL_50", "SELL_50_PERCENT", "SELL_50%":
		return "SELL_50"
	case "CDF_BUY_ZONE", "OMS_BUY_ZONE", "BREAKOUT":
		return "BREAKOUT"
	case "CDF_SELL_ZONE", "OMS_SELL_ZONE", "SELL_DOWN":
		return "SELL_DOWN"
	case "RE_ENTRY":
		return "REENTRY"
	default:
		return normalized
	}
}

func validAlertScript(script string) bool {
	switch normalizeAlertScript(script) {
	case "cdf", "tms", "etf_tms", "ctf", "q4d", "q3d", "etf_rebalancing":
		return true
	default:
		return false
	}
}

func scriptMatches(script string, candidates ...string) bool {
	normalized := normalizeAlertScript(script)
	for _, candidate := range candidates {
		if normalized == normalizeAlertScript(candidate) {
			return true
		}
	}
	return false
}

func canonicalTickerSymbol(ticker string) string {
	symbol := strings.ToUpper(strings.TrimSpace(ticker))
	if colonIdx := strings.LastIndex(symbol, ":"); colonIdx != -1 {
		symbol = symbol[colonIdx+1:]
	}
	return strings.TrimSpace(symbol)
}

func activeAlertSetupExists(fullTicker, symbol, script string) bool {
	script = normalizeAlertScript(script)
	fullTicker = strings.ToUpper(strings.TrimSpace(fullTicker))
	symbol = canonicalTickerSymbol(symbol)
	if symbol == "" {
		symbol = canonicalTickerSymbol(fullTicker)
	}
	if script == "" || symbol == "" {
		return false
	}

	var count int
	err := db.QueryRow(`
		SELECT COUNT(*)
		FROM active_alerts
		WHERE script = ?
		  AND (
			UPPER(TRIM(COALESCE(ticker, ''))) = ?
			OR UPPER(CASE
				WHEN instr(COALESCE(ticker, ''), ':') > 0 THEN substr(ticker, instr(ticker, ':') + 1)
				ELSE COALESCE(ticker, '')
			END) = ?
		  )
	`, script, fullTicker, symbol).Scan(&count)
	if err != nil {
		log.Printf("[ALERT SETUP] Failed to check active %s setup for %s/%s: %v", script, fullTicker, symbol, err)
		return false
	}
	return count > 0
}

func hasActionableStockTMSContext(fullTicker, symbol, companyName string) (bool, string) {
	fullTicker = strings.ToUpper(strings.TrimSpace(fullTicker))
	symbol = canonicalTickerSymbol(symbol)
	if symbol == "" {
		symbol = canonicalTickerSymbol(fullTicker)
	}
	companyName = strings.TrimSpace(companyName)

	var activeHoldings int
	err := db.QueryRow(`
		SELECT COUNT(*)
		FROM holdings h
		WHERE h.is_active = 1
		  AND (
			UPPER(TRIM(COALESCE(h.ticker, ''))) = ?
			OR UPPER(TRIM(COALESCE(h.ticker, ''))) = ?
			OR UPPER(TRIM(COALESCE(h.exchange_prefix, '') || COALESCE(h.ticker, ''))) = ?
			OR LOWER(TRIM(COALESCE(h.company_name, ''))) = LOWER(TRIM(?))
		  )
	`, fullTicker, symbol, fullTicker, companyName).Scan(&activeHoldings)
	if err != nil {
		log.Printf("[TMS] Failed to check active holdings for %s/%s (%s): %v", fullTicker, symbol, companyName, err)
	} else if activeHoldings > 0 {
		return true, "active holding"
	}

	var externalRows int
	err = db.QueryRow(`
		SELECT COUNT(*)
		FROM stock_analysis sa
		WHERE COALESCE(sa.is_external, 0) = 1
		  AND (
			UPPER(TRIM(COALESCE(sa.ticker, ''))) = ?
			OR UPPER(CASE
				WHEN instr(COALESCE(sa.ticker, ''), ':') > 0 THEN substr(sa.ticker, instr(sa.ticker, ':') + 1)
				ELSE COALESCE(sa.ticker, '')
			END) = ?
			OR LOWER(TRIM(COALESCE(sa.name, ''))) = LOWER(TRIM(?))
		  )
	`, fullTicker, symbol, companyName).Scan(&externalRows)
	if err != nil {
		log.Printf("[TMS] Failed to check external analysis rows for %s/%s (%s): %v", fullTicker, symbol, companyName, err)
	} else if externalRows > 0 {
		return true, "external held position"
	}

	var watchlistRows int
	err = db.QueryRow(`
		SELECT COUNT(*)
		FROM stock_analysis sa
		WHERE COALESCE(sa.is_watchlist, 0) = 1
		  AND COALESCE(sa.is_external, 0) = 0
		  AND (
			UPPER(TRIM(COALESCE(sa.ticker, ''))) = ?
			OR UPPER(CASE
				WHEN instr(COALESCE(sa.ticker, ''), ':') > 0 THEN substr(sa.ticker, instr(sa.ticker, ':') + 1)
				ELSE COALESCE(sa.ticker, '')
			END) = ?
			OR LOWER(TRIM(COALESCE(sa.name, ''))) = LOWER(TRIM(?))
		  )
	`, fullTicker, symbol, companyName).Scan(&watchlistRows)
	if err != nil {
		log.Printf("[TMS] Failed to check watchlist rows for %s/%s (%s): %v", fullTicker, symbol, companyName, err)
	} else if watchlistRows > 0 {
		return false, "watchlist-only"
	}

	return false, "not active holding or external position"
}

func removeActiveAlertSetupsForTicker(fullTicker, symbol, script string) {
	script = normalizeAlertScript(script)
	fullTicker = strings.ToUpper(strings.TrimSpace(fullTicker))
	symbol = canonicalTickerSymbol(symbol)
	if symbol == "" {
		symbol = canonicalTickerSymbol(fullTicker)
	}
	if script == "" || symbol == "" {
		return
	}

	result, err := db.Exec(`
		DELETE FROM active_alerts
		WHERE script = ?
		  AND (
			UPPER(TRIM(COALESCE(ticker, ''))) = ?
			OR UPPER(CASE
				WHEN instr(COALESCE(ticker, ''), ':') > 0 THEN substr(ticker, instr(ticker, ':') + 1)
				ELSE COALESCE(ticker, '')
			END) = ?
		  )
	`, script, fullTicker, symbol)
	if err != nil {
		log.Printf("[ALERT SETUP] Failed to remove invalid %s setup for %s/%s: %v", script, fullTicker, symbol, err)
		return
	}
	removed, _ := result.RowsAffected()
	if removed > 0 {
		log.Printf("[ALERT SETUP] Removed %d invalid %s setup(s) for %s/%s", removed, script, fullTicker, symbol)
	}
}

// determineSignalSource implements the architecture's source detection logic
func determineSignalSource(analystPriceTarget, timeframe, signal, ticker, script string) string {
	script = normalizeAlertScript(script)

	// If script is explicitly provided, trust it as authoritative source
	switch script {
	case "etf_tms":
		return "etf_tms"
	case "cdf":
		return "cdf"
	case "tms":
		return "tms"
	case "q4d", "ctf", "q3d":
		return script
	}

	// Fallback heuristics for signals without explicit script field

	// CDF signals have analystPriceTarget field
	if analystPriceTarget != "" {
		return "cdf"
	}

	// TMS add/trim signals have timeframe field
	if timeframe != "" {
		return "tms"
	}

	// TMS event signals
	if signal == "REENTRY" {
		return "tms"
	}

	// CDF zone signals from the TMS script's embedded trend filter.
	if signal == "BREAKOUT" || signal == "SELL_DOWN" {
		return "tms"
	}

	// BUY/SELL without special fields could be:
	// - Regime signal (from SPY, XAO, GOLD, etc.)
	// - ATR stop hit (full exit)
	if signal == "BUY" || signal == "SELL" {
		for _, regimeTicker := range staticdata.KnownRegimeWebhookTickers {
			if ticker == regimeTicker || strings.Contains(ticker, regimeTicker) {
				return "q4d"
			}
		}

		// If SELL signal without analystPriceTarget and not a regime ticker, assume it's a TMS stop hit.
		if signal == "SELL" {
			return "tms"
		}

		// Otherwise unknown/regime
		return "q4d"
	}

	return "unknown"
}

type normalizedWebhookSignal struct {
	AlertType string
	Strength  string
	Timeframe string
	Ignored   bool
	Reason    string
}

func normalizeSignalStrength(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "strong":
		return "Strong"
	case "weak":
		return "Weak"
	default:
		return ""
	}
}

func normalizeSignalTimeframe(value string) string {
	normalized := strings.ToUpper(strings.TrimSpace(value))
	switch normalized {
	case "1D", "2D", "3D":
		return normalized
	default:
		return ""
	}
}

func supportedCanonicalAlertType(value string) string {
	switch canonicalAlertType(value) {
	case "ADD", "TRIM", "BUY", "SELL", "SELL_50", "BREAKOUT", "SELL_DOWN", "REENTRY", "REGIME":
		return canonicalAlertType(value)
	default:
		return ""
	}
}

func normalizeTradingViewSignal(rawSignal, rawStrength, rawSignalStrength, rawTimeframe string) normalizedWebhookSignal {
	signal := strings.ToLower(strings.TrimSpace(rawSignal))
	strength := normalizeSignalStrength(rawStrength)
	if strength == "" {
		strength = normalizeSignalStrength(rawSignalStrength)
	}
	timeframe := normalizeSignalTimeframe(rawTimeframe)

	switch signal {
	case "buy":
		return normalizedWebhookSignal{AlertType: "BUY", Strength: strength, Timeframe: timeframe}
	case "sell":
		return normalizedWebhookSignal{AlertType: "SELL", Strength: strength, Timeframe: timeframe}
	case "strong_add":
		return normalizedWebhookSignal{AlertType: "ADD", Strength: "Strong", Timeframe: timeframe}
	case "weak_add":
		return normalizedWebhookSignal{AlertType: "ADD", Strength: "Weak", Timeframe: timeframe}
	case "strong_trim":
		return normalizedWebhookSignal{AlertType: "TRIM", Strength: "Strong", Timeframe: timeframe}
	case "weak_trim":
		return normalizedWebhookSignal{AlertType: "TRIM", Strength: "Weak", Timeframe: timeframe}
	case "add":
		return normalizedWebhookSignal{AlertType: "ADD", Strength: strength, Timeframe: timeframe}
	case "trim":
		return normalizedWebhookSignal{AlertType: "TRIM", Strength: strength, Timeframe: timeframe}
	case "add_1d":
		return normalizedWebhookSignal{AlertType: "ADD", Strength: strength, Timeframe: "1D"}
	case "add_2d":
		return normalizedWebhookSignal{AlertType: "ADD", Strength: strength, Timeframe: "2D"}
	case "add_3d":
		return normalizedWebhookSignal{AlertType: "ADD", Strength: strength, Timeframe: "3D"}
	case "trim_1d":
		return normalizedWebhookSignal{AlertType: "TRIM", Strength: strength, Timeframe: "1D"}
	case "trim_2d":
		return normalizedWebhookSignal{AlertType: "TRIM", Strength: strength, Timeframe: "2D"}
	case "trim_3d":
		return normalizedWebhookSignal{AlertType: "TRIM", Strength: strength, Timeframe: "3D"}
	case "reentry":
		return normalizedWebhookSignal{AlertType: "REENTRY", Strength: strength, Timeframe: timeframe}
	case "breakout", "cdf_buy_zone":
		return normalizedWebhookSignal{AlertType: "BREAKOUT", Strength: strength, Timeframe: timeframe}
	case "cdf_sell_zone":
		return normalizedWebhookSignal{AlertType: "SELL_DOWN", Strength: strength, Timeframe: timeframe}
	case "price_target_update":
		return normalizedWebhookSignal{}
	case "dca":
		return normalizedWebhookSignal{Ignored: true, Reason: "DCA signal is deprecated"}
	case "oms_buy_zone":
		return normalizedWebhookSignal{Ignored: true, Reason: "legacy buy-zone signal is deprecated"}
	case "oms_sell_zone":
		return normalizedWebhookSignal{Ignored: true, Reason: "legacy sell-zone signal is deprecated"}
	default:
		if canonical := supportedCanonicalAlertType(rawSignal); canonical != "" {
			return normalizedWebhookSignal{AlertType: canonical, Strength: strength, Timeframe: timeframe}
		}
		return normalizedWebhookSignal{Ignored: true, Reason: "unsupported signal"}
	}
}

// handleConnectionSignal registers an active alert in the database
func handleConnectionSignal(w http.ResponseWriter, ticker, script string, allocations map[string]float64) {
	script = normalizeAlertScript(script)

	// Validate script name
	if !validAlertScript(script) {
		log.Printf("[CONNECTION] Invalid script name: %s", script)
		if w != nil {
			http.Error(w, "Invalid script name", http.StatusBadRequest)
		}
		return
	}

	// Insert or update active alert
	_, err := db.Exec(`
		INSERT INTO active_alerts (ticker, script)
		VALUES (?, ?)
		ON CONFLICT(ticker, script) DO UPDATE SET
			created_at = CURRENT_TIMESTAMP
	`, ticker, script)

	if err != nil {
		log.Printf("[CONNECTION] Failed to register alert for %s (%s): %v", ticker, script, err)
		if w != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
		return
	}

	// If this is an ETF rebalancing signal with allocations, store them
	if script == "etf_rebalancing" && len(allocations) > 0 {
		// Clear existing allocations
		_, err = db.Exec(`DELETE FROM etf_allocations`)
		if err != nil {
			log.Printf("[ETF] Failed to clear existing allocations: %v", err)
		}

		// Insert new allocations — set both allocation_percent (mutable) and base_weight (immutable strategic weight)
		for etfTicker, allocation := range allocations {
			_, err = db.Exec(`
				INSERT INTO etf_allocations (ticker, allocation_percent, base_weight, last_updated)
				VALUES (?, ?, ?, CURRENT_TIMESTAMP)
				ON CONFLICT(ticker) DO UPDATE SET
					allocation_percent = excluded.allocation_percent,
					base_weight = excluded.base_weight,
					last_updated = CURRENT_TIMESTAMP
			`, etfTicker, allocation, allocation)

			if err != nil {
				log.Printf("[ETF] Failed to store allocation for %s: %v", etfTicker, err)
			}
		}
		log.Printf("[ETF] Stored allocations for %d ETFs", len(allocations))
	}

	log.Printf("[CONNECTION] Registered alert: %s on %s", script, ticker)

	if w != nil {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{
			"message": "Alert registered",
			"ticker":  ticker,
			"script":  script,
		})
	}
}

// getActiveAlerts returns all registered connection signals
func getActiveAlerts(w http.ResponseWriter, r *http.Request) {
	rows, err := db.Query(`
		SELECT id, ticker, script, created_at
		FROM active_alerts
		ORDER BY created_at DESC
	`)
	if err != nil {
		log.Printf("[API] Failed to query active alerts: %v", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	type ActiveAlert struct {
		ID        int       `json:"id"`
		Ticker    string    `json:"ticker"`
		Script    string    `json:"script"`
		CreatedAt time.Time `json:"created_at"`
	}

	var activeAlerts []ActiveAlert
	for rows.Next() {
		var alert ActiveAlert
		if err := rows.Scan(&alert.ID, &alert.Ticker, &alert.Script, &alert.CreatedAt); err != nil {
			log.Printf("[API] Failed to scan active alert: %v", err)
			continue
		}
		activeAlerts = append(activeAlerts, alert)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(activeAlerts)
}

func setupActiveAlert(w http.ResponseWriter, r *http.Request) {
	etfManagementMu.Lock()
	defer etfManagementMu.Unlock()
	var payload struct {
		Ticker             string   `json:"ticker"`
		Script             string   `json:"script"`
		PositionState      string   `json:"position_state"`
		AnalystPriceTarget *float64 `json:"analyst_price_target"`
		CompanyName        string   `json:"company_name"`
	}

	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	payload.Ticker = strings.TrimSpace(payload.Ticker)
	payload.Script = normalizeAlertScript(payload.Script)
	payload.PositionState = strings.ToUpper(strings.TrimSpace(payload.PositionState))
	payload.CompanyName = strings.TrimSpace(payload.CompanyName)

	if payload.Ticker == "" || !scriptMatches(payload.Script, "cdf", "tms", "etf_tms") {
		http.Error(w, "ticker and valid script are required", http.StatusBadRequest)
		return
	}
	mode, modeErr := etfManagementModeFrom(db, payload.Ticker)
	if modeErr != nil {
		http.Error(w, modeErr.Error(), 500)
		return
	}
	if !etfManagementAccepts(mode, payload.Script) {
		http.Error(w, "This script does not match the fund's selected management mode", http.StatusConflict)
		return
	}
	requiresPositionState := !scriptMatches(payload.Script, "tms")
	if requiresPositionState && payload.PositionState != "BUY" && payload.PositionState != "SELL" {
		http.Error(w, "position_state must be BUY or SELL", http.StatusBadRequest)
		return
	}
	hasPositionState := payload.PositionState == "BUY" || payload.PositionState == "SELL"

	fullTicker := payload.Ticker
	ticker := payload.Ticker
	exchangePrefix := "ASX:"
	if colonIdx := strings.Index(ticker, ":"); colonIdx != -1 {
		exchangePrefix = ticker[:colonIdx+1]
		ticker = ticker[colonIdx+1:]
	}
	ticker = strings.ToUpper(strings.TrimSpace(ticker))
	if ticker == "" {
		http.Error(w, "ticker is required", http.StatusBadRequest)
		return
	}

	tx, err := db.Begin()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer tx.Rollback()

	if _, err = tx.Exec(`
		INSERT INTO active_alerts (ticker, script)
		VALUES (?, ?)
		ON CONFLICT(ticker, script) DO UPDATE SET
			created_at = CURRENT_TIMESTAMP
	`, fullTicker, payload.Script); err != nil {
		log.Printf("[ALERT SETUP] Failed to register %s for %s: %v", payload.Script, fullTicker, err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	if hasPositionState {
		if _, err = tx.Exec(`
			INSERT INTO security_positions (ticker, position_state, last_updated)
			VALUES (?, ?, CURRENT_TIMESTAMP)
			ON CONFLICT(ticker) DO UPDATE SET
				position_state = excluded.position_state,
				stopped_waiting_reentry = CASE
					WHEN excluded.position_state = 'BUY' THEN 0
					ELSE stopped_waiting_reentry
				END,
				last_updated = CURRENT_TIMESTAMP
		`, ticker, payload.PositionState); err != nil {
			log.Printf("[ALERT SETUP] Failed to initialise position for %s: %v", ticker, err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
	}

	if scriptMatches(payload.Script, "etf_tms") {
		if _, err = tx.Exec(`
			INSERT INTO etf_positions (ticker, position_state, allocation_pct, cash_allocated, manual_override, last_updated)
			VALUES (?, ?, 0, 0, 0, CURRENT_TIMESTAMP)
			ON CONFLICT(ticker) DO UPDATE SET
				position_state = excluded.position_state,
				last_updated = CURRENT_TIMESTAMP
		`, ticker, payload.PositionState); err != nil {
			log.Printf("[ALERT SETUP] Failed to upsert ETF position for %s: %v", ticker, err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if _, err = tx.Exec(`
			INSERT INTO etf_allocations (ticker, allocation_percent, base_weight, tactical_status, last_updated)
			VALUES (?, 0, 0, ?, CURRENT_TIMESTAMP)
			ON CONFLICT(ticker) DO UPDATE SET
				tactical_status = excluded.tactical_status,
				last_updated = CURRENT_TIMESTAMP
		`, ticker, payload.PositionState); err != nil {
			log.Printf("[ALERT SETUP] Failed to upsert ETF allocation for %s: %v", ticker, err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if payload.CompanyName != "" {
			var result sql.Result
			if result, err = tx.Exec(`
				UPDATE stock_analysis
				SET security_type = 'ETF', updated_at = CURRENT_TIMESTAMP
				WHERE name = ?
				   OR UPPER(CASE
						WHEN instr(COALESCE(ticker, ''), ':') > 0 THEN substr(ticker, instr(ticker, ':') + 1)
						ELSE COALESCE(ticker, '')
					END) = ?
			`, payload.CompanyName, ticker); err != nil {
				log.Printf("[ALERT SETUP] Failed to mark %s as ETF security type: %v", ticker, err)
				http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}
			rowsAffected, _ := result.RowsAffected()
			if rowsAffected == 0 {
				if _, err = tx.Exec(`
					INSERT INTO stock_analysis (ticker, name, security_type, updated_at)
					VALUES (?, ?, 'ETF', CURRENT_TIMESTAMP)
					ON CONFLICT(ticker, name) DO UPDATE SET
						security_type = 'ETF',
						updated_at = CURRENT_TIMESTAMP
				`, fullTicker, payload.CompanyName); err != nil {
					log.Printf("[ALERT SETUP] Failed to create ETF analysis row for %s (%s): %v", ticker, payload.CompanyName, err)
					http.Error(w, err.Error(), http.StatusInternalServerError)
					return
				}
			}
		} else {
			if _, err = tx.Exec(`
				UPDATE stock_analysis
				SET security_type = 'ETF', updated_at = CURRENT_TIMESTAMP
				WHERE UPPER(CASE
					WHEN instr(COALESCE(ticker, ''), ':') > 0 THEN substr(ticker, instr(ticker, ':') + 1)
					ELSE COALESCE(ticker, '')
				END) = ?
			`, ticker); err != nil {
				log.Printf("[ALERT SETUP] Failed to mark %s as ETF security type: %v", ticker, err)
			}
		}
		if _, err = tx.Exec(`
			UPDATE etf_allocations
			SET tactical_status = ?, last_updated = CURRENT_TIMESTAMP
			WHERE ticker = ?
		`, payload.PositionState, ticker); err != nil {
			log.Printf("[ALERT SETUP] Failed to sync ETF tactical status for %s: %v", ticker, err)
		}
	}

	if payload.AnalystPriceTarget != nil && *payload.AnalystPriceTarget > 0 && payload.CompanyName != "" {
		if _, err = tx.Exec(`
			INSERT INTO stock_analysis (ticker, name, analyst_pt, updated_at)
			VALUES (?, ?, ?, CURRENT_TIMESTAMP)
			ON CONFLICT(ticker, name) DO UPDATE SET
				analyst_pt = excluded.analyst_pt,
				updated_at = CURRENT_TIMESTAMP
		`, ticker, payload.CompanyName, *payload.AnalystPriceTarget); err != nil {
			log.Printf("[ALERT SETUP] Failed to update analyst PT for %s (%s): %v", ticker, payload.CompanyName, err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
	}

	if err = tx.Commit(); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	log.Printf("[ALERT SETUP] Initialised %s for %s as %s", payload.Script, fullTicker, payload.PositionState)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"message":         "Alert setup initialised",
		"ticker":          fullTicker,
		"position_ticker": ticker,
		"script":          payload.Script,
		"position_state":  payload.PositionState,
		"exchange_prefix": exchangePrefix,
	})
}

func removeActiveAlert(w http.ResponseWriter, r *http.Request) {
	var payload struct {
		ID     int64  `json:"id"`
		Ticker string `json:"ticker"`
		Script string `json:"script"`
	}

	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	fullTicker := strings.TrimSpace(payload.Ticker)
	script := normalizeAlertScript(payload.Script)
	if payload.ID > 0 {
		result, err := db.Exec(`DELETE FROM active_alerts WHERE id = ?`, payload.ID)
		if err != nil {
			log.Printf("[ALERT SETUP] Failed to remove active alert id %d: %v", payload.ID, err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		removed, _ := result.RowsAffected()
		log.Printf("[ALERT SETUP] Removed %d active alert(s) by id %d", removed, payload.ID)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{
			"message": "Active alert removed",
			"id":      payload.ID,
			"removed": removed,
		})
		return
	}
	if fullTicker == "" || script == "" {
		http.Error(w, "ticker and script are required", http.StatusBadRequest)
		return
	}

	symbol := strings.ToUpper(fullTicker)
	if colonIdx := strings.LastIndex(symbol, ":"); colonIdx != -1 {
		symbol = symbol[colonIdx+1:]
	}
	symbol = strings.TrimSpace(symbol)
	if symbol == "" {
		http.Error(w, "ticker is required", http.StatusBadRequest)
		return
	}

	var result sql.Result
	var err error
	for attempt := 0; attempt < 4; attempt++ {
		result, err = db.Exec(`
			DELETE FROM active_alerts
			WHERE script = ?
			  AND (
				ticker = ?
				OR UPPER(CASE
					WHEN instr(ticker, ':') > 0 THEN substr(ticker, instr(ticker, ':') + 1)
					ELSE ticker
				END) = ?
			  )
		`, script, fullTicker, symbol)
		if err == nil || !strings.Contains(strings.ToLower(err.Error()), "database is locked") {
			break
		}
		time.Sleep(time.Duration(attempt+1) * 250 * time.Millisecond)
	}
	if err != nil {
		log.Printf("[ALERT SETUP] Failed to remove %s for %s: %v", script, fullTicker, err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	removed, _ := result.RowsAffected()
	log.Printf("[ALERT SETUP] Removed %d active alert(s) for %s (%s)", removed, fullTicker, script)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"message": "Active alert removed",
		"ticker":  fullTicker,
		"script":  script,
		"removed": removed,
	})
}

// getUnmappedAlerts returns alerts that need manual ticker/company mapping
func getUnmappedAlerts(w http.ResponseWriter, r *http.Request) {
	rows, err := db.Query(`
		SELECT id, ticker, exchange_prefix, alert_type, strength, created_at
		FROM alerts
		WHERE needs_mapping = 1 AND is_active = 1
			AND alert_type NOT IN ('CONNECTED', 'CONNECTION', 'TEST')
			AND ticker NOT IN ('TEST', 'PING', 'CONNECTION')
		ORDER BY created_at DESC
	`)
	if err != nil {
		log.Printf("[API] Failed to query unmapped alerts: %v", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	type UnmappedAlert struct {
		ID             int       `json:"id"`
		Ticker         string    `json:"ticker"`
		ExchangePrefix string    `json:"exchange_prefix"`
		AlertType      string    `json:"alert_type"`
		Strength       *string   `json:"strength"`
		CreatedAt      time.Time `json:"created_at"`
	}

	var alerts []UnmappedAlert
	for rows.Next() {
		var alert UnmappedAlert
		if err := rows.Scan(&alert.ID, &alert.Ticker, &alert.ExchangePrefix, &alert.AlertType, &alert.Strength, &alert.CreatedAt); err != nil {
			log.Printf("[API] Failed to scan unmapped alert: %v", err)
			continue
		}
		alert.AlertType = canonicalAlertType(alert.AlertType)
		alerts = append(alerts, alert)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(alerts)
}

// resolveAlertMapping creates a company mapping and optionally adds to watchlist
func resolveAlertMapping(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	alertID := vars["id"]

	var payload struct {
		CompanyName    string `json:"company_name"`
		Ticker         string `json:"ticker"`
		ExchangePrefix string `json:"exchange_prefix"`
		TemplateID     string `json:"template_id"`
		AddToWatchlist bool   `json:"add_to_watchlist"`
		AssetClass     string `json:"asset_class"`
	}

	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		http.Error(w, "Invalid JSON", http.StatusBadRequest)
		return
	}

	if payload.CompanyName == "" || payload.Ticker == "" {
		http.Error(w, "company_name and ticker are required", http.StatusBadRequest)
		return
	}

	if strings.TrimSpace(payload.ExchangePrefix) == "" {
		http.Error(w, "exchange_prefix is required", http.StatusBadRequest)
		return
	}

	// Create company mapping
	_, err := db.Exec(`
		INSERT INTO company_mappings (company_name, ticker, exchange_prefix, template_id)
		VALUES (?, ?, ?, NULLIF(?, ''))
		ON CONFLICT(company_name) DO UPDATE SET
			ticker = excluded.ticker,
			exchange_prefix = excluded.exchange_prefix,
			template_id = COALESCE(NULLIF(excluded.template_id, ''), company_mappings.template_id),
			enriched_at = CURRENT_TIMESTAMP
	`, payload.CompanyName, payload.Ticker, payload.ExchangePrefix, payload.TemplateID)
	if err != nil {
		log.Printf("[API] Failed to create company mapping: %v", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Mark alert as resolved (no longer needs mapping)
	_, err = db.Exec(`
		UPDATE alerts SET needs_mapping = 0 WHERE id = ?
	`, alertID)
	if err != nil {
		log.Printf("[API] Failed to update alert: %v", err)
	}

	// Optionally add to watchlist (stock_analysis table)
	if payload.AddToWatchlist {
		watchlistTicker := fullTickerForStorage(payload.ExchangePrefix, payload.Ticker)
		if watchlistTicker == "" {
			watchlistTicker = strings.ToUpper(strings.TrimSpace(payload.Ticker))
		}
		// Remove any placeholder entry where name == ticker (created before mapping was known)
		_, err = db.Exec(`
			DELETE FROM stock_analysis WHERE ticker = ? AND name = ?
		`, watchlistTicker, watchlistTicker)
		if err != nil {
			log.Printf("[API] Failed to clean up placeholder stock_analysis for %s: %v", watchlistTicker, err)
		}

		tx, txErr := db.Begin()
		if txErr != nil {
			log.Printf("[API] Failed to begin watchlist upsert: %v", txErr)
		} else {
			if err = setStockAnalysisWatchlistStateTx(tx, watchlistTicker, "", payload.CompanyName, true); err != nil {
				tx.Rollback()
				log.Printf("[API] Failed to add to watchlist: %v", err)
			} else if err = tx.Commit(); err != nil {
				log.Printf("[API] Failed to commit watchlist upsert: %v", err)
			}
		}

		// Also create a security position in BUY state
		_, err = db.Exec(`
			INSERT INTO security_positions (ticker, position_state)
			VALUES (?, 'BUY')
			ON CONFLICT(ticker) DO NOTHING
		`, payload.Ticker)
		if err != nil {
			log.Printf("[API] Failed to create security position: %v", err)
		}

		// Persist primary asset class directly on the analysis row.
		if payload.AssetClass != "" {
			if normalizedClass, ok := resolvePortfolioAssignmentClass(payload.AssetClass); ok {
				var classValue interface{}
				if normalizedClass != "" {
					classValue = normalizedClass
				}
				_, err = db.Exec(`
					UPDATE stock_analysis
					SET primary_asset_class = ?, updated_at = CURRENT_TIMESTAMP
					WHERE ticker = ?
				`, classValue, payload.Ticker)
				if err != nil {
					log.Printf("[API] Failed to persist primary asset class: %v", err)
				} else {
					stampAssetClassSourceByTicker(payload.Ticker, AssetClassSourceSignal)
				}
			} else {
				log.Printf("[API] Ignoring non-conforming primary asset class %q for %s", payload.AssetClass, payload.Ticker)
			}
		}
	}

	log.Printf("[MAPPING] Resolved %s → %s%s (watchlist: %v)", payload.CompanyName, payload.ExchangePrefix, payload.Ticker, payload.AddToWatchlist)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"status":  "success",
		"message": fmt.Sprintf("Mapped %s to %s%s", payload.CompanyName, payload.ExchangePrefix, payload.Ticker),
	})
}
