package main

import (
	"time"

	"github.com/gorilla/mux"
)

func newRouter() *mux.Router {
	router := mux.NewRouter()

	// Middleware order matters: CORS first so 401 responses still carry CORS
	// headers, then auth, then logging.
	router.Use(corsMiddleware)
	router.Use(authMiddleware)
	router.Use(slowRequestLogger)

	// Lightweight liveness check for Fly. Keep this independent of DB/business queries so
	// health checks do not pile onto a slow portfolio request and take routing down.
	router.HandleFunc("/api/health", healthCheck).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/auth/check", checkAPICaller).Methods("GET", "POST", "OPTIONS")
	router.HandleFunc("/api/auth/session", ownerAccessHandler).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/auth/register/start", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/register/finish", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/login/start", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/login/finish", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/recover", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/logout", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/refresh", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/auth/revoke-all", ownerAccessHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/data-freshness", getDataFreshness).Methods("GET", "OPTIONS")

	// Routes - Alerts & Decisions
	router.HandleFunc("/api/alerts", getAlerts).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/alerts", createAlert).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/alerts/{id}/dismiss", dismissAlert).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/alerts/stream", streamAlerts).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/alerts/active", getActiveAlerts).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/alerts/active/setup", setupActiveAlert).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/alerts/active/remove", removeActiveAlert).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/alerts/unmapped", getUnmappedAlerts).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/alerts/{id}/resolve", resolveAlertMapping).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/security-actions", getSecurityActions).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/watchlist/opportunities", getWatchlistOpportunities).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/security-actions/{id}/record-execution", recordSecurityActionExecution).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/security-actions/{id}/ignore", ignoreSecurityAction).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/security-actions/{id}/override-exit", overrideSecurityActionExit).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/etf/policy", getETFPolicy).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/mappings", getETFAssetClassMappings).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/mappings/{ticker}", updateETFAssetClassMapping).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/etf/core-policies/{assetClass}", updateETFCorePolicy).Methods("PUT", "OPTIONS")
	router.HandleFunc("/api/etf/management", getETFManagementProfiles).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/management/{ticker}", updateETFManagementProfile).Methods("PUT", "OPTIONS")
	router.HandleFunc("/api/etf/allocation-ledger", getETFAllocationLedger).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/shortlist", getETFShortlist).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/shortlist/{ticker}", upsertETFShortlistEntry).Methods("PUT", "OPTIONS")
	router.HandleFunc("/api/etf/shortlist/{ticker}", deleteETFShortlistEntry).Methods("DELETE", "OPTIONS")
	router.HandleFunc("/api/etf/unmapped-holdings", getETFUnmappedHoldings).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/asset-classes/conflicts", getAssetClassConflicts).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/asset-classes/trace/{ticker}", getAssetClassTrace).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio/mandate", getPortfolioMandate).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/momentum", getETFMomentumWorkspace).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/momentum/price-history/refresh", refreshETFMomentumPriceHistoryHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/etf/momentum/runs", runETFMomentumParityHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/etf/momentum/tradingview-snapshots", createETFMomentumTradingViewSnapshotHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/etf/allocations", getETFAllocations).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/allocations/rebalance", rebalanceETFAllocations).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/etf/actual-allocations", getETFActualAllocations).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/decisions", getDecisions).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/decisions", createDecision).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/webhook/tradingview", tradingViewWebhook).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/webhook/tradingview", webhookStatus).Methods("GET")
	router.HandleFunc("/api/webhook/theme-confirmation", themeConfirmationWebhook).Methods("POST", "OPTIONS")

	// Webhook dead-letter queue (failed async webhook processing)
	router.HandleFunc("/api/webhook-dead-letters", getWebhookDeadLetters).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/webhook-dead-letters/{id}/retry", retryWebhookDeadLetterHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/webhook-dead-letters/{id}/dismiss", dismissWebhookDeadLetterHandler).Methods("POST", "OPTIONS")

	// Security Positions
	router.HandleFunc("/api/positions", getSecurityPositions).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/positions/{ticker}", updateSecurityPosition).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/migrate/previous-alerts", migratePreviousAlerts).Methods("POST", "OPTIONS")

	// Holdings & Portfolio
	router.HandleFunc("/api/statements/import", importStatement).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/statements", getStatements).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/backup-status", getBackupStatus).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/statements/latest", getLatestStatement).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/statements/{id}", getStatementDetail).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/statements/{id}/revisions", getStatementRevisions).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/statements/{id}/revisions/{revision}", getStatementRevision).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/performance/portfolio", getPortfolioPerformance).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/performance/asset-classes", getAssetClassPerformance).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/performance/security/{ticker}", getSecurityPerformance).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/performance/events", getPerformanceEvents).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/performance/security-directions", getSecurityPerformanceDirections).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/holdings/{id}", updateHolding).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/portfolio", getPortfolio).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/cash-movements", createCashMovement).Methods("POST", "OPTIONS")

	// Stock Analysis (insights & annotations)
	router.HandleFunc("/api/source-research/templates", getSourceResearchTemplates).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/source-research/jobs", getSourceResearchJobs).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/source-research/jobs", createSourceResearchJob).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/source-research/jobs/{id}", getSourceResearchJob).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/source-research/jobs/{id}/recover", recoverSourceResearchJob).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis", getAllAnalysis).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/analysis", upsertAnalysis).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/performance/refresh", refreshAnalysisPerformance).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/security-type", setAnalysisSecurityType).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/classify-asset-class", classifyAnalysisAssetClass).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/listing-reviews", getListingReviews).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/announcement-subscriptions", getAnnouncementSubscriptions).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/announcement-subscriptions", updateAnnouncementSubscriptions).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/analysis/exchanges/auto-assign", autoAssignExchanges).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/{id}", updateAnalysis).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/analysis/{id}", deleteAnalysis).Methods("DELETE", "OPTIONS")
	router.HandleFunc("/api/analysis/{id}/rename", renameAnalysis).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/analysis/{id}/contribute", logContribution).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/contribute-by-name", contributeByName).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/analysis/refresh-prices", refreshWatchlistPrices).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/news/brief", getNewsBrief).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/news/run", runNewsBrief).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/news/foundation-jobs", createNewsFoundationJobHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/news/foundation-jobs/{id}", getNewsFoundationJobHandler).Methods("GET", "OPTIONS")
	// Daily job async endpoints
	router.HandleFunc("/api/news/daily-jobs", createNewsDailyJobHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/news/daily-jobs/{id}", getNewsDailyJobHandler).Methods("GET", "OPTIONS")
	// Thesis management
	router.HandleFunc("/api/news/theses/{id}", getNewsThesisDetailHandler).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/news/theses/{id}", patchNewsThesisHandler).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/news/theses/{id}", deleteNewsThesisHandler).Methods("DELETE", "OPTIONS")
	router.HandleFunc("/api/news/theses/{id}/updates", getNewsThesisUpdatesHandler).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/news/theses/{id}/conviction-history", getNewsThesisConvictionHistoryHandler).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/news/theses/{id}/mark-invalidation-checked", markInvalidationCheckedHandler).Methods("POST", "OPTIONS")
	// Deduplication + market context history
	router.HandleFunc("/api/news/deduplicate", deduplicateNewsThesesHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/news/market-context-history", getNewsMarketContextHistoryHandler).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-memos/latest", getLatestPortfolioMemoRun).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-memos/{jobId}", getPortfolioMemoRunByJobID).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-memos", savePortfolioMemoRun).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-history", getPortfolioHistory).Methods("GET", "OPTIONS")

	// Company ticker enrichment
	router.HandleFunc("/api/enrich/tickers", enrichTickers).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/mappings", getCompanyMappings).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/mappings/{id}", updateCompanyMapping).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/mappings/bulk", bulkUpdateMappings).Methods("POST", "OPTIONS")

	// Stock Groups (portfolio organization)
	router.HandleFunc("/api/groups", getStockGroups).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/groups", saveStockGroups).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/groups/{id}", deleteStockGroup).Methods("DELETE", "OPTIONS")
	router.HandleFunc("/api/asset-classes", getAssetClasses).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/asset-classes", createCustomAssetClass).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/asset-classes/{code}", deleteCustomAssetClass).Methods("DELETE", "OPTIONS")
	router.HandleFunc("/api/regime-assignments", getRegimeAssignments).Methods("GET", "OPTIONS")

	// Sync changes (change detection for UI notifications)
	router.HandleFunc("/api/sync/changes", getSyncChanges).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/sync/changes/acknowledge", acknowledgeSyncChanges).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/sync/history", getSyncHistory).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/sync/tradingview", syncTradingViewData).Methods("POST", "OPTIONS")

	// ETF Management
	router.HandleFunc("/api/etf/positions", getETFPositions).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/positions/{ticker}", updateETFPosition).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/etf/rebalance", getActiveRebalance).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/etf/rebalance/{sequence}/dismiss", dismissRebalance).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/webhook/etf-rebalance", etfRebalanceWebhook).Methods("POST", "OPTIONS")

	// Regime Management
	router.HandleFunc("/api/regimes", getRegimes).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/regimes/status", withRequestTimeout(8*time.Second, getRegimeStatus)).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/regimes/returns", getRegimeReturns).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/regimes/returns/refresh", refreshRegimeReturnsHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/webhook/regime", regimeWebhook).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/regime/proposed-actions", getRegimeProposedActionsHandler).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/regime/apply-impacts", applyRegimeImpactsHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/equity-sizing", getEquitySizing).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/sizing/allocations", sizingAllocationsHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-risk/header-state", getPortfolioRiskHeaderState).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay-summary", withRequestTimeout(10*time.Second, getPortfolioOverlaySummary)).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/sync", withRequestTimeout(10*time.Second, syncPortfolioOverlayHandler)).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/reconciliation", withRequestTimeout(10*time.Second, getPortfolioOverlayReconciliation)).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/apply-stage1", applyPortfolioOverlayStage1).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/reopen-stage1", reopenPortfolioOverlayStage1).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/mark-stage1-partial", markPortfolioOverlayStage1Partial).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/save-stage2", savePortfolioOverlayStage2).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/complete-stage2", completePortfolioOverlayStage2).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/set-baseline", setPortfolioOverlayBaseline).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-overlay/mark-reviewed", markPortfolioOverlaySignalReviewed).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-mix/current", withRequestTimeout(10*time.Second, getCurrentPortfolioMix)).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-mix/approved", getApprovedPortfolioMix).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-mix/cycle-performance", getPortfolioCyclePerformance).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-mix/approve-current", withRequestTimeout(15*time.Second, approveCurrentPortfolioMix)).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/commodity-themes", getCommodityThemes).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/commodity-themes", createCommodityTheme).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/commodity-themes/price-history/refresh", refreshCommodityPriceHistoryHandler).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/commodity-themes/initialise-feed", initialiseCommodityThemeFeed).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/commodity-themes/{code}/configuration", updateCommodityThemeConfiguration).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/commodity-themes/{code}", getCommodityTheme).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/commodity-themes/{code}", deactivateCommodityTheme).Methods("DELETE", "OPTIONS")
	router.HandleFunc("/api/commodity-themes/{code}/direct-expression", updateCommodityThemeDirectExpression).Methods("PATCH", "OPTIONS")
	portfolioRebalances := newPortfolioRebalanceHandler()
	router.HandleFunc("/api/portfolio-rebalances/current", portfolioRebalances.Current).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances/current/adjustment-plan", withRequestTimeout(10*time.Second, getCurrentPortfolioAdjustmentPlan)).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances/{id}/adjustment-plan", withRequestTimeout(10*time.Second, getPortfolioAdjustmentPlan)).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances", portfolioRebalances.Create).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances/from-memo", portfolioRebalances.CreateFromMemo).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances/{id}/mark-partial", portfolioRebalances.MarkPartial).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances/{id}/complete", portfolioRebalances.Complete).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/portfolio-rebalances/{id}/approve", approvePortfolioRebalance).Methods("POST", "OPTIONS")
	router.HandleFunc("/api/asset-class-config", getAssetClassConfig).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/asset-class-config/{code}", updateAssetClassConfig).Methods("PATCH", "OPTIONS")

	// Settings
	router.HandleFunc("/api/settings", getSettings).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/weight-policy", getWeightPolicy).Methods("GET", "OPTIONS")
	router.HandleFunc("/api/weight-policy", updateWeightPolicy).Methods("PATCH", "OPTIONS")
	router.HandleFunc("/api/settings", updateSettings).Methods("POST", "OPTIONS")

	return router
}
