const test = require('node:test');
const assert = require('node:assert/strict');
const { mkdirSync } = require('node:fs');
const { chromium, expect } = require('@playwright/test');
const { mockContextPanel } = require('./fixtures/context-panel.cjs');
const base = process.env.CONTEXT_PANEL_BASE_URL || 'http://127.0.0.1:3100';
const key = 'alpha-edge:position-row-appearance-v1';
const row = page => page.locator('tr[data-position-class="GOLD_MINERS"]');
const background = locator => locator.locator('td').first().evaluate(el => getComputedStyle(el).backgroundColor);
async function setup(t, viewport = { width: 1600, height: 1000 }) {
    mkdirSync('test-results', { recursive: true });
    const browser = await chromium.launch();
    t.after(() => browser.close());
    const page = await browser.newPage({ viewport });
    const fixture = await mockContextPanel(page, { includeSilverHolding: true });
    const colours = {};
    const colourWrites = [];
    const failures = { get: false, post: false };
    await page.route('**/api/**/settings', async route => {
        const post = route.request().method() === 'POST';
        if (failures[post ? 'post' : 'get']) return route.fulfill({ status: 503, body: 'Isolated failure' });
        if (!post) return route.fulfill({ json: colours });
        const payload = route.request().postDataJSON();
        colourWrites.push(payload);
        Object.assign(colours, payload);
        return route.fulfill({ json: { status: 'success', updated: payload } });
    });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${base}/#/positions`);
    await expect(row(page)).toBeVisible();
    return { page, fixture, errors, colours, colourWrites, failures };
}




test('default triangle follows expansion and a chosen icon replaces it', { timeout: 90000 }, async t => {
    const { page, errors } = await setup(t);
    const security = page.locator('tr.positions-stock-row').filter({ hasText: 'Gold Producer' });
    const name = row(page).locator('[data-position-class-label]');
    const cell = row(page).locator('td').first();
    const trigger = row(page).locator('button[data-row-icon]');
    const groupWrites = [];
    await page.route('**/api/**/groups', async route => {
        if (route.request().method() === 'GET') return route.fallback();
        groupWrites.push(route.request().postDataJSON());
        return route.fulfill({ json: { status: 'ok' } });
    });
    await expect(cell).not.toContainText(/[\u25bc\u25b6]/);
    await expect(trigger.locator('[data-row-disclosure="down"]')).toBeVisible();
    await expect(security).toBeVisible();
    await name.click();
    await expect(security).toHaveCount(0);
    await expect(trigger.locator('[data-row-disclosure="right"]')).toBeVisible();
    await expect(cell).not.toContainText(/[\u25bc\u25b6]/);
    await name.click();
    await expect(security).toBeVisible();
    await expect(trigger.locator('[data-row-disclosure="down"]')).toBeVisible();
    await expect.poll(() => groupWrites.length).toBe(2);
    await row(page).locator('button[data-row-icon]').press('ArrowDown');
    await page.getByRole('dialog', { name: /^Icon for / }).getByRole('button', { name: 'Gold miners', exact: true }).click();
    await expect(trigger.locator('svg.lucide-coins')).toBeVisible();
    await expect(trigger.locator('[data-row-disclosure]')).toHaveCount(0);
    await expect(security).toBeVisible();
    await expect(cell).not.toContainText(/[\u25bc\u25b6]/);
    assert.equal(groupWrites.length, 2, 'icon selection does not collapse the class');
    await page.mouse.move(0, 0);
    await row(page).screenshot({ path: 'test-results/position-row-replacement-icon.png' });
    assert.deepEqual(errors, []);
});

test('row appearance menu is retired without changing Compare or table geometry', { timeout: 120000 }, async t => {
    const { page, fixture, errors } = await setup(t);
    const height = (await row(page).boundingBox()).height;
    const original = await background(row(page));
    await page.getByTestId('positions-view-menu-trigger').click();
    await expect(page.getByRole('button', { name: 'Row appearance', exact: true })).toHaveCount(0);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Comparing', exact: true }).click();
    await expect(row(page).locator('.position-shape-comparison-cell')).toHaveCount(0);
    await page.getByRole('button', { name: 'Compare', exact: true }).click();
    await expect(row(page).locator('.position-shape-current-value')).toHaveText('60.0%');
    await expect(row(page).locator('.position-shape-target-value')).toHaveText('60.0%');
    assert.equal((await row(page).boundingBox()).height, height);
    assert.equal(await background(row(page)), original);
    assert.deepEqual(fixture.writes, []);
    assert.deepEqual(errors, []);
});

test('per-row colour selection shares the canonical palette without changing icons or row geometry', { timeout: 120000 }, async t => {
    const { page, fixture, errors, colourWrites, failures } = await setup(t);
    const trigger = row(page).locator('button[data-row-icon]');
    const security = page.locator('tr.positions-stock-row').filter({ hasText: 'Gold Producer' });
    const silver = page.locator('tr[data-position-class="SILVER_MINERS"]');
    const silverAccent = await silver.evaluate(el => getComputedStyle(el).getPropertyValue('--row-accent'));
    const height = (await row(page).boundingBox()).height;
    const original = await background(row(page));
    const pie = page.getByTestId('sleeve-summary-dock').locator('svg path[fill*="--asset-class-colour-GOLD_MINERS"]').first();
    await trigger.press('ArrowDown');
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    await palette.getByRole('button', { name: 'Gold miners', exact: true }).click();
    const iconGrey = await trigger.evaluate(el => getComputedStyle(el).color);
    await expect(trigger.locator('svg')).toHaveCSS('color', iconGrey);
    await trigger.press('ArrowDown');
    const colourButton = palette.getByRole('button', { name: /^Change Gold Miners.*colour$/ });
    await expect(colourButton).toBeEnabled();
    await palette.screenshot({ path: 'test-results/position-row-icons-and-colour.png' });
    await colourButton.click();
    const editor = page.getByRole('dialog', { name: /^Gold Miners.* colour$/ });
    await expect(editor.getByRole('radio')).toHaveCount(30);
    await editor.getByRole('radio', { name: 'Steel blue', exact: true }).click();
    assert.deepEqual(colourWrites, [], 'single swatch click is a draft');
    await expect(pie).toHaveCSS('fill', 'rgb(212, 167, 44)');
    await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(palette).toBeVisible();
    await expect(colourButton).toBeFocused();
    await colourButton.click();
    await editor.getByRole('radio', { name: 'Steel blue', exact: true }).click();
    await editor.getByRole('button', { name: 'Save', exact: true }).click();
    await expect(editor).toHaveCount(0);
    await expect(palette).toBeVisible();
    await expect(trigger.locator('svg')).toHaveCSS('color', iconGrey);
    await expect(pie).toHaveCSS('fill', 'rgb(82, 138, 184)');
    assert.deepEqual(colourWrites, [{ 'asset_class_colour:GOLD_MINERS': '#528ab8' }]);
    assert.equal(await silver.evaluate(el => getComputedStyle(el).getPropertyValue('--row-accent')), silverAccent);
    await expect(trigger).toHaveAttribute('data-row-icon', 'gold');
    assert.equal((await row(page).boundingBox()).height, height);
    assert.equal(await background(row(page)), original);
    await expect(security).toBeVisible();
    await colourButton.click();
    failures.post = true;
    await editor.getByRole('radio', { name: 'Teal', exact: true }).dblclick();
    await expect(editor.getByRole('alert')).toContainText('could not be saved');
    await expect(pie).toHaveCSS('fill', 'rgb(82, 138, 184)');
    failures.post = false;
    await editor.getByRole('radio', { name: 'Teal', exact: true }).dblclick();
    await expect(editor).toHaveCount(0);
    assert.equal(colourWrites.length, 2, 'double-click saves only once');
    await expect(pie).toHaveCSS('fill', 'rgb(20, 184, 166)');
    await page.keyboard.press('Escape');
    await page.reload();
    await expect(trigger).toHaveAttribute('data-row-icon', 'gold');
    await expect(trigger.locator('svg')).toHaveCSS('color', iconGrey);
    await trigger.press('ArrowDown');
    await colourButton.click();
    await editor.getByRole('button', { name: 'Reset', exact: true }).click();
    await expect(editor).toHaveCount(0);
    await expect(trigger).toHaveAttribute('data-row-icon', 'gold');
    await expect(pie).toHaveCSS('fill', 'rgb(212, 167, 44)');
    await page.keyboard.press('Escape');
    await page.getByTitle('Switch to light mode', { exact: true }).click();
    const lightIconGrey = await trigger.evaluate(el => getComputedStyle(el).color);
    assert.notEqual(lightIconGrey, iconGrey, 'icon grey follows the theme');
    await expect(trigger.locator('svg')).toHaveCSS('color', lightIconGrey);
    await page.setViewportSize({ width: 390, height: 700 });
    await trigger.press('ArrowDown');
    await colourButton.click();
    const bounds = await editor.boundingBox();
    assert.ok(bounds.x >= 15 && bounds.x + bounds.width <= 375);
    await editor.screenshot({ path: 'test-results/position-row-colour-mobile.png' });
    await editor.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(colourButton).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(security).toBeVisible();
    assert.deepEqual(fixture.writes, [], 'only the canonical colour setting may be written');
    assert.deepEqual(errors, []);
});

test('icon colour previews are independent per class, persistent and follow the shared palette', { timeout: 120000 }, async t => {
    const { page, fixture, errors, colourWrites } = await setup(t);
    const trigger = row(page).locator('button[data-row-icon]');
    const silverTrigger = page.locator('tr[data-position-class="SILVER_MINERS"]').locator('button[data-row-icon]');
    const security = page.locator('tr.positions-stock-row').filter({ hasText: 'Gold Producer' });
    const height = (await row(page).boundingBox()).height;
    await silverTrigger.press('ArrowDown');
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    await palette.getByRole('button', { name: 'Silver miners', exact: true }).click();
    await expect(silverTrigger).toBeFocused();
    await trigger.press('ArrowDown');
    const previews = palette.getByRole('radiogroup', { name: 'Icon colour', exact: true });
    const neutral = previews.getByRole('radio', { name: 'Neutral', exact: true });
    const coloured = previews.getByRole('radio', { name: 'Class colour', exact: true });
    await expect(palette.getByRole('checkbox')).toHaveCount(0);
    await expect(previews).toHaveText('');
    await expect(neutral).toBeChecked();
    await expect(coloured).not.toBeChecked();
    await expect(previews.locator('[data-row-disclosure="down"]')).toHaveCount(2);
    await expect(coloured.locator('svg')).toHaveCSS('color', 'rgb(212, 167, 44)');
    await coloured.click();
    await expect(palette).toBeVisible();
    await palette.getByRole('button', { name: 'Class icon', exact: true }).click();
    await expect(trigger.locator('svg')).toHaveCSS('color', 'rgb(212, 167, 44)');
    const grey = await silverTrigger.evaluate(el => getComputedStyle(el).color);
    await expect(silverTrigger.locator('svg')).toHaveCSS('color', grey);
    assert.deepEqual(colourWrites, [], 'opting into colour is a browser preference, not a palette write');
    await trigger.press('ArrowDown');
    await expect(coloured).toBeChecked();
    await expect(neutral.locator('svg')).toHaveCSS('color', grey);
    await palette.screenshot({ path: 'test-results/position-row-icon-colour-previews.png' });
    await palette.getByRole('button', { name: /^Change Gold Miners.*colour$/ }).click();
    const editor = page.getByRole('dialog', { name: /^Gold Miners.* colour$/ });
    await editor.getByRole('radio', { name: 'Steel blue', exact: true }).dblclick();
    await expect(editor).toHaveCount(0);
    await expect(trigger.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await expect(coloured.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await expect(silverTrigger.locator('svg')).toHaveCSS('color', grey);
    await page.keyboard.press('Escape');
    await page.reload();
    await expect(trigger).toHaveAttribute('data-icon-colour', 'class');
    await expect(trigger.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await page.getByTitle('Switch to light mode', { exact: true }).click();
    const lightGrey = await silverTrigger.evaluate(el => getComputedStyle(el).color);
    assert.notEqual(lightGrey, grey);
    await expect(silverTrigger.locator('svg')).toHaveCSS('color', lightGrey);
    await expect(trigger.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await trigger.press('ArrowDown');
    await neutral.click();
    await expect(trigger.locator('svg')).toHaveCSS('color', lightGrey);
    await page.keyboard.press('Escape');
    await page.reload();
    await expect(trigger).toHaveAttribute('data-icon-colour', 'neutral');
    await trigger.press('ArrowDown');
    await neutral.focus();
    await page.keyboard.down('ArrowRight');
    await expect(coloured).toBeChecked();
    await page.keyboard.up('ArrowRight');
    await expect(trigger.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await page.evaluate(key => {
        const original = Storage.prototype.setItem;
        window.restoreStorage = () => { Storage.prototype.setItem = original; };
        Storage.prototype.setItem = function(name, value) { if (name === key) throw new Error('Unavailable'); return original.call(this, name, value); };
    }, key);
    await neutral.click();
    await expect(palette.getByRole('alert')).toContainText('could not be saved');
    await expect(coloured).toBeChecked();
    await expect(trigger.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await page.evaluate(() => window.restoreStorage());
    await neutral.click();
    await expect(palette.getByRole('alert')).toHaveCount(0);
    await expect(trigger.locator('svg')).toHaveCSS('color', lightGrey);
    await page.setViewportSize({ width: 320, height: 568 });
    await expect(previews).toBeInViewport();
    assert.ok(await palette.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
    await coloured.click();
    await expect(neutral.locator('svg')).toHaveCSS('color', lightGrey);
    await expect(coloured.locator('svg')).toHaveCSS('color', 'rgb(82, 138, 184)');
    await palette.screenshot({ path: 'test-results/position-row-icon-colour-previews-mobile.png' });
    await page.keyboard.press('Escape');
    await page.setViewportSize({ width: 1600, height: 1000 });
    await expect(security).toBeVisible();
    assert.equal((await row(page).boundingBox()).height, height);
    assert.deepEqual(colourWrites, [{ 'asset_class_colour:GOLD_MINERS': '#528ab8' }]);
    assert.deepEqual(fixture.writes, [], 'no group or financial writes');
    assert.deepEqual(errors, []);
});

test('row colour settings failure offers retry without preventing icon selection', { timeout: 90000 }, async t => {
    const { page, failures, errors } = await setup(t);
    failures.get = true;
    await page.reload();
    const trigger = row(page).locator('button[data-row-icon]');
    await trigger.press('ArrowDown');
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    await expect(palette.getByRole('alert')).toContainText('Saved colours are unavailable');
    await expect(palette.getByRole('button', { name: /^Change Gold Miners.*colour$/ })).toBeDisabled();
    await palette.getByRole('button', { name: 'Mining', exact: true }).click();
    await expect(trigger).toHaveAttribute('data-row-icon', 'mining');
    await trigger.press('ArrowDown');
    failures.get = false;
    await palette.getByRole('button', { name: 'Retry', exact: true }).click();
    await expect(palette.getByRole('button', { name: /^Change Gold Miners.*colour$/ })).toBeEnabled();
    await expect(palette.getByRole('alert')).toHaveCount(0);
    assert.deepEqual(errors, []);
});

test('row icon picker saves only that class, supports removal and does not collapse or resize rows', { timeout: 120000 }, async t => {
    const { page, fixture, errors } = await setup(t);
    const trigger = row(page).locator('button[data-row-icon]');
    const silver = page.locator('tr[data-position-class="SILVER_MINERS"]');
    const silverTrigger = silver.locator('button[data-row-icon]');
    const security = page.locator('tr.positions-stock-row').filter({ hasText: 'Gold Producer' });
    const bounds = await row(page).boundingBox();
    const original = await background(row(page));
    await trigger.press('ArrowDown');
    let palette = page.getByRole('dialog', { name: /^Icon for / });
    await expect(palette).toBeVisible();
    await expect(security).toBeVisible();
    await palette.getByRole('button', { name: 'Precious metals', exact: true }).click();
    await expect(palette).toHaveCount(0);
    await expect(trigger).toHaveAttribute('data-row-icon', 'gem');
    await expect(silverTrigger).toHaveAttribute('data-row-icon', 'none');
    await expect(trigger).toBeFocused();
    await expect(security).toBeVisible();
    assert.equal((await row(page).boundingBox()).height, bounds.height);
    assert.equal(await background(row(page)), original);
    assert.equal((await trigger.locator('svg').boundingBox()).width, 16);
    await silverTrigger.press('ArrowDown');
    await page.getByRole('dialog', { name: /^Icon for / }).getByRole('button', { name: 'Mining', exact: true }).click();
    await expect(silverTrigger).toHaveAttribute('data-row-icon', 'mining');
    await expect(trigger).toHaveAttribute('data-row-icon', 'gem');
    await page.reload();
    await expect(trigger).toHaveAttribute('data-row-icon', 'gem');
    await expect(silverTrigger).toHaveAttribute('data-row-icon', 'mining');
    await trigger.focus();
    await page.keyboard.press('ArrowDown');
    await expect(page.getByRole('dialog', { name: /^Icon for / })).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    await trigger.press('ArrowDown');
    palette = page.getByRole('dialog', { name: /^Icon for / });
    await page.evaluate(key => {
        const original = Storage.prototype.setItem;
        window.restoreStorage = () => { Storage.prototype.setItem = original; };
        Storage.prototype.setItem = function(name, value) { if (name === key) throw new Error('Unavailable'); return original.call(this, name, value); };
    }, key);
    await palette.getByRole('button', { name: 'Default arrow', exact: true }).click();
    await expect(palette.getByRole('alert')).toBeVisible();
    await expect(trigger).toHaveAttribute('data-row-icon', 'gem');
    await page.evaluate(() => window.restoreStorage());
    await palette.getByRole('button', { name: 'Default arrow', exact: true }).click();
    await expect(trigger).toHaveAttribute('data-row-icon', 'none');
    await expect(silverTrigger).toHaveAttribute('data-row-icon', 'mining');
    await trigger.press('ArrowDown');
    palette = page.getByRole('dialog', { name: /^Icon for / });
    await palette.screenshot({ path: 'test-results/position-row-icon-picker.png' });
    for (const viewport of [{ width: 390, height: 700 }, { width: 320, height: 568 }]) {
        await page.setViewportSize(viewport);
        const rect = await palette.boundingBox();
        assert.ok(rect.x >= 0 && rect.x + rect.width <= viewport.width, 'palette stays in mobile viewport');
        assert.ok(await palette.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
    }
    await palette.screenshot({ path: 'test-results/position-row-icon-picker-mobile.png' });
    await expect(security).toBeVisible();
    assert.deepEqual(fixture.writes, [], 'icon picker must never save group collapse state or financial data');
    assert.deepEqual(errors, []);
});

test('existing browser preferences lose borders, global icons and tint while retaining class icons', { timeout: 120000 }, async t => {
    const { page } = await setup(t);
    await page.evaluate(key => localStorage.setItem(key, JSON.stringify({ version: 1,
        defaults: { shade: 'tint', intensity: 18, border: 'rule', emblem: 'energy' },
        overrides: { GOLD_MINERS: { shade: 'soft', border: 'accent', emblem: 'gem' } },
    })), key);
    await page.reload();
    await expect(row(page)).not.toHaveAttribute('data-row-border');
    await expect(row(page)).not.toHaveAttribute('data-row-shade');
    await expect(row(page).locator('button[data-row-icon]')).toHaveAttribute('data-row-icon', 'gem');
    const silver = page.locator('tr[data-position-class="SILVER_MINERS"]');
    await expect(silver).not.toHaveAttribute('data-row-border');
    await expect(silver.locator('button[data-row-icon]')).toHaveAttribute('data-row-icon', 'none');
});

test('default arrows and selected icons share one stable slot on hover, selection and removal', { timeout: 120000 }, async t => {
    const { page, fixture, errors } = await setup(t);
    const label = row(page).locator('[data-position-class-label]');
    const slot = row(page).locator('[data-icon-slot]');
    const trigger = row(page).locator('button[data-row-icon]');
    await page.mouse.move(0, 0);
    const height = (await row(page).boundingBox()).height;
    const originalNameInset = await label.evaluate(el => el.getBoundingClientRect().x - el.closest('td').getBoundingClientRect().x);
    await expect(trigger.locator('[data-row-disclosure="down"]')).toBeVisible();
    assert.equal((await slot.boundingBox()).width, 28);
    const cell = await row(page).locator('td').first().boundingBox();
    await page.mouse.move(cell.x + cell.width - 20, cell.y + cell.height / 2);
    assert.equal((await slot.boundingBox()).width, 28, 'hovering the rest of the row does not shift its name');
    await row(page).screenshot({ path: 'test-results/position-row-icon-rest.png' });
    for (const fraction of [0.1, 0.5, 0.95]) {
        await page.mouse.move(0, 0);
        await expect(trigger).toHaveCSS('opacity', '1');
        const name = await label.boundingBox();
        await page.mouse.move(name.x + name.width * fraction, name.y + name.height / 2);
        await expect(trigger).toHaveCSS('opacity', '1');
        assert.equal((await slot.boundingBox()).width, 28);
    }
    await expect(trigger).toHaveCSS('opacity', '1');
    assert.equal((await slot.boundingBox()).width, 28);
    const expandedLabel = await label.boundingBox();
    const expandedTrigger = await trigger.boundingBox();
    assert.equal(await label.evaluate(el => el.getBoundingClientRect().x - el.closest('td').getBoundingClientRect().x), originalNameInset, 'hover leaves the class name in place');
    assert.ok(expandedLabel.x >= expandedTrigger.x + expandedTrigger.width, 'expanded control does not overlap the name');
    assert.equal((await row(page).boundingBox()).height, height);
    await row(page).screenshot({ path: 'test-results/position-row-icon-hover.png' });
    await trigger.press('ArrowDown');
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    await palette.hover();
    assert.equal((await slot.boundingBox()).width, 28, 'palette keeps its anchor open after the pointer leaves');
    await palette.getByRole('button', { name: 'Precious metals', exact: true }).click();
    await page.mouse.move(0, 0);
    await expect(trigger).toHaveCSS('opacity', '1');
    assert.equal((await slot.boundingBox()).width, 28, 'assigned icons remain in the row at rest');
    await page.reload();
    await expect(trigger).toHaveAttribute('data-row-icon', 'gem');
    await expect(trigger).toHaveCSS('opacity', '1');
    assert.equal((await slot.boundingBox()).width, 28, 'saved icons remain visible after reload');
    const unassignedTrigger = page.locator('tr[data-position-class="SILVER_MINERS"]').locator('button[data-row-icon]');
    await expect(unassignedTrigger).toHaveCSS('opacity', '1');
    await trigger.press('ArrowDown');
    await palette.getByRole('button', { name: 'Default arrow', exact: true }).click();
    await page.mouse.move(0, 0);
    await expect(trigger).toHaveCSS('opacity', '1');
    await expect(trigger.locator('[data-row-disclosure="down"]')).toBeVisible();
    assert.equal((await slot.boundingBox()).width, 28);
    const restingCell = await row(page).locator('td').first().boundingBox();
    assert.equal((await label.boundingBox()).x - restingCell.x, originalNameInset, 'removing the icon restores the original name position');
    await page.keyboard.press('Tab');
    await trigger.focus();
    await expect(trigger).toHaveCSS('opacity', '1');
    await page.keyboard.press('ArrowDown');
    await expect(palette).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    assert.deepEqual(fixture.writes, []);
    assert.deepEqual(errors, []);
});

test('a quick click toggles without a tooltip, while an 800ms hover arms its selector without moving the label', { timeout: 90000 }, async t => {
    const { page, fixture, errors } = await setup(t);
    const trigger = row(page).locator('button[data-row-icon]');
    const label = row(page).locator('[data-position-class-label]');
    const security = page.locator('tr.positions-stock-row').filter({ hasText: 'Gold Producer' });
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    const groupWrites = [];
    await page.route('**/api/**/groups', async route => {
        if (route.request().method() === 'GET') return route.fallback();
        groupWrites.push(route.request().postDataJSON());
        return route.fulfill({ json: { status: 'ok' } });
    });
    await page.clock.install();
    await page.clock.pauseAt(new Date(Date.now() + 1000));
    await expect(trigger).not.toHaveAttribute('title');
    await trigger.click();
    await expect(security).toHaveCount(0);
    await expect(trigger).toHaveAttribute('aria-expanded', 'false');
    await expect(trigger).toHaveAccessibleName(/^Expand Gold Miners/);
    await expect(trigger).not.toHaveAttribute('title');
    await expect(palette).toHaveCount(0);
    await trigger.click();
    await expect(security).toBeVisible();
    await expect(trigger).toHaveAttribute('aria-expanded', 'true');
    await expect(trigger).not.toHaveAttribute('title');
    await expect.poll(() => groupWrites.length).toBe(2);
    const inset = () => label.evaluate(el => el.getBoundingClientRect().x - el.closest('td').getBoundingClientRect().x);
    const before = await inset();
    await page.clock.runFor(799);
    await expect(trigger).toHaveAttribute('data-icon-mode', 'disclosure');
    await page.clock.runFor(1);
    await expect(trigger).toHaveAttribute('data-icon-mode', 'selector');
    await expect(trigger.locator('[data-selector-icon]')).toBeVisible();
    await expect(trigger).toHaveAccessibleName(/^Choose icon for Gold Miners/);
    await expect(trigger).toHaveAttribute('title', /^Choose icon for Gold Miners/);
    await expect(palette).toHaveCount(0);
    assert.equal(await inset(), before);
    await row(page).screenshot({ path: 'test-results/position-row-hover-selector.png' });
    await trigger.click();
    await expect(palette).toBeVisible();
    await expect(security).toBeVisible();
    await palette.getByRole('button', { name: 'Gold miners', exact: true }).click();
    await expect(trigger).toHaveAttribute('data-icon-mode', 'disclosure');
    await expect(trigger.locator('svg.lucide-coins')).toBeVisible();
    await expect(trigger).not.toHaveAttribute('title');
    assert.equal(groupWrites.length, 2, 'opening and choosing an icon never changes expansion');
    await trigger.press('Enter');
    await expect(security).toHaveCount(0);
    await trigger.press('Space');
    await expect(security).toBeVisible();
    await trigger.press('ArrowDown');
    await expect(palette).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(palette).toHaveCount(0);
    await page.clock.runFor(1); // Radix restores focus on its deferred close callback.
    await expect(trigger).toBeFocused();
    await expect(trigger).toHaveAttribute('data-icon-mode', 'disclosure');
    await expect.poll(() => groupWrites.length).toBe(4);
    assert.deepEqual(fixture.writes, []);
    assert.deepEqual(errors, []);
});

test('hover intent resets on leaving, blur and unmount, including for custom icons', { timeout: 90000 }, async t => {
    const { page, fixture, errors } = await setup(t);
    const trigger = row(page).locator('button[data-row-icon]');
    await trigger.press('ArrowDown');
    await page.getByRole('dialog', { name: /^Icon for / }).getByRole('button', { name: 'Gold miners', exact: true }).click();
    await page.clock.install();
    await page.clock.pauseAt(new Date(Date.now() + 1000));
    await trigger.hover();
    await page.clock.runFor(700);
    await page.mouse.move(0, 0);
    await page.clock.runFor(2500);
    await expect(trigger.locator('svg.lucide-coins')).toBeVisible();
    await trigger.hover();
    await page.clock.runFor(799);
    await expect(trigger).toHaveAttribute('data-icon-mode', 'disclosure');
    await page.clock.runFor(1);
    await expect(trigger.locator('[data-selector-icon]')).toBeVisible();
    await page.mouse.move(0, 0);
    await expect(trigger.locator('svg.lucide-coins')).toBeVisible();
    await trigger.hover();
    await page.clock.runFor(800);
    await expect(trigger).toHaveAttribute('data-icon-mode', 'selector');
    await trigger.focus();
    await page.keyboard.press('Tab');
    await expect(trigger).toHaveAttribute('data-icon-mode', 'disclosure');
    await page.mouse.move(0, 0);
    await trigger.hover();
    await page.clock.runFor(500);
    await page.evaluate(() => { window.location.hash = '/help'; });
    await expect(trigger).toHaveCount(0);
    await page.clock.runFor(2500);
    await expect(page.getByRole('dialog', { name: /^Icon for / })).toHaveCount(0);
    assert.deepEqual(fixture.writes, []);
    assert.deepEqual(errors, []);
});

test('touch taps toggle the class and an 800ms hold opens the selector, but scrolling cancels it', { timeout: 120000 }, async t => {
    const browser = await chromium.launch();
    t.after(() => browser.close());
    const page = await browser.newPage({ viewport: { width: 390, height: 700 }, isMobile: true, hasTouch: true });
    const fixture = await mockContextPanel(page);
    const groupWrites = [];
    await page.route('**/api/**/groups', async route => {
        if (route.request().method() === 'GET') return route.fallback();
        groupWrites.push(route.request().postDataJSON());
        return route.fulfill({ json: { status: 'ok' } });
    });
    await page.goto(`${base}/#/positions`);
    const trigger = row(page).locator('button[data-row-icon]');
    await expect(trigger).toBeVisible();
    await expect(trigger).toHaveCSS('opacity', '1');
    await trigger.tap();
    await expect(trigger).toHaveAttribute('aria-expanded', 'false');
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    await expect(palette).toHaveCount(0);
    await trigger.tap();
    await expect(trigger).toHaveAttribute('aria-expanded', 'true');
    await page.clock.install();
    await page.clock.pauseAt(new Date(Date.now() + 1000));
    const point = { pointerType: 'touch', clientX: 40, clientY: 100 };
    await trigger.dispatchEvent('pointerdown', point);
    await page.clock.runFor(500);
    await trigger.dispatchEvent('pointermove', { ...point, clientY: 120 });
    await page.clock.runFor(1000);
    await expect(palette).toHaveCount(0);
    await trigger.dispatchEvent('pointercancel', point);
    await trigger.dispatchEvent('pointerdown', point);
    await page.clock.runFor(799);
    await expect(palette).toHaveCount(0);
    await page.clock.runFor(1);
    await expect(palette).toBeVisible();
    await trigger.dispatchEvent('pointerup', point);
    await trigger.dispatchEvent('click');
    await expect(palette).toBeVisible();
    await palette.getByRole('button', { name: 'Mining', exact: true }).tap();
    await expect(trigger).toHaveAttribute('data-row-icon', 'mining');
    await expect.poll(() => groupWrites.length).toBe(2);
    assert.deepEqual(fixture.writes, []);
});

test('expanded icon catalogue is searchable, fits small screens and persists new symbols', { timeout: 120000 }, async t => {
    const { page, fixture, errors } = await setup(t);
    const trigger = row(page).locator('button[data-row-icon]');
    await trigger.press('ArrowDown');
    const palette = page.getByRole('dialog', { name: /^Icon for / });
    await expect(palette.locator('[data-icon-choice]')).toHaveCount(74);
    await expect(palette.getByRole('button', { name: 'Default arrow', exact: true })).toBeFocused();
    const search = palette.getByRole('searchbox', { name: 'Search icons' });
    await search.fill('nuclear');
    await expect(palette.locator('[data-icon-choice]')).toHaveCount(3);
    await expect(palette.getByRole('button', { name: 'Uranium & nuclear', exact: true })).toBeVisible();
    await search.fill('no-such-icon');
    await expect(palette.getByRole('status')).toHaveText('No matching icons');
    await expect(palette.getByRole('button', { name: 'Default arrow', exact: true })).toBeVisible();
    await search.fill('');
    for (const viewport of [{ width: 1280, height: 900 }, { width: 390, height: 700 }, { width: 320, height: 568 }, { width: 740, height: 390 }]) {
        await page.setViewportSize(viewport);
        await expect(palette).toBeInViewport();
        const rect = await palette.boundingBox();
        assert.ok(rect.x >= 0 && rect.y >= 0 && rect.x + rect.width <= viewport.width && rect.y + rect.height <= viewport.height);
        assert.ok(await palette.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
        await expect(search).toBeInViewport();
        await palette.getByRole('button', { name: 'Unassigned', exact: true }).scrollIntoViewIfNeeded();
        await expect(palette.getByRole('button', { name: 'Unassigned', exact: true })).toBeInViewport();
    }
    await page.setViewportSize({ width: 390, height: 700 });
    await search.fill('gold');
    await expect(palette.getByRole('button', { name: 'Gold miners', exact: true })).toBeVisible();
    await palette.screenshot({ path: 'test-results/position-row-icon-search.png' });
    await search.fill('lithium');
    await palette.getByRole('button', { name: 'Lithium & batteries', exact: true }).click();
    await expect(trigger).toHaveAttribute('data-row-icon', 'lithium');
    await page.reload();
    await expect(trigger).toHaveAttribute('data-row-icon', 'lithium');
    await expect(trigger.locator('svg.lucide-battery-charging')).toBeVisible();
    await trigger.press('ArrowDown');
    await expect(search).toHaveValue('');
    await expect(palette.getByRole('radiogroup', { name: 'Icon colour', exact: true }).locator('svg.lucide-battery-charging')).toHaveCount(2);
    await palette.getByRole('button', { name: 'Class icon', exact: true }).click();
    await expect(trigger).toHaveAttribute('data-row-icon', 'auto');
    await expect(trigger.locator('svg.lucide-coins')).toBeVisible();
    await page.setViewportSize({ width: 1600, height: 1000 });
    await page.getByTitle('Switch to light mode', { exact: true }).click();
    await trigger.press('ArrowDown');
    await palette.screenshot({ path: 'test-results/position-row-icon-expanded-light.png' });
    await expect(palette.getByRole('button', { name: 'Default arrow', exact: true })).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(trigger).toBeFocused();
    assert.deepEqual(fixture.writes, []);
    assert.deepEqual(errors, []);
});
