// User choices, not a second identity registry. Existing defaults and overrides stay valid.
export const ASSET_CLASS_COLOUR_PRESETS = [
    { name: 'Coral', colour: '#fb5b62' },
    { name: 'Vermilion', colour: '#e76f51' },
    { name: 'Orange', colour: '#f19b4b' },
    { name: 'Amber', colour: '#f59e0b' },
    { name: 'Gold', colour: '#d4a72c' },
    { name: 'Copper', colour: '#b87333' },
    { name: 'Lime', colour: '#84cc16' },
    { name: 'Olive', colour: '#8da94e' },
    { name: 'Sage', colour: '#75a766' },
    { name: 'Emerald', colour: '#34d399' },
    { name: 'Teal', colour: '#14b8a6' },
    { name: 'Sea green', colour: '#4e9d92' },
    { name: 'Cyan', colour: '#06b6d4' },
    { name: 'Sky', colour: '#38bdf8' },
    { name: 'Steel blue', colour: '#528ab8' },
    { name: 'Blue', colour: '#569de2' },
    { name: 'Periwinkle', colour: '#818cf8' },
    { name: 'Lavender', colour: '#a78bfa' },
    { name: 'Violet', colour: '#9972d8' },
    { name: 'Purple', colour: '#a855f7' },
    { name: 'Orchid', colour: '#c87db1' },
    { name: 'Magenta', colour: '#d946ef' },
    { name: 'Rose', colour: '#f472b6' },
    { name: 'Raspberry', colour: '#ec4899' },
    { name: 'Silver', colour: '#c0c7d2' },
    { name: 'Platinum', colour: '#a2afaa' },
    { name: 'Blue-grey', colour: '#94a3b8' },
    { name: 'Slate', colour: '#64748b' },
    { name: 'Pewter', colour: '#71717a' },
    { name: 'Stone', colour: '#a88d6d' },
] as const;
