// Generated from the backend's seeded defaults. Do not edit by hand.
// Regenerate: npm run demo:catalogue
export const DEMO_ASSET_CLASS_CATALOGUE = {
    "assetClasses": [
        {
            "code": "INSURANCE",
            "asset_class_code": "INSURANCE",
            "display_name": "Insurance",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 95,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "STAPLES",
            "asset_class_code": "STAPLES",
            "display_name": "Staples",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 110,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "GAMBLING",
            "asset_class_code": "GAMBLING",
            "display_name": "Gambling",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 111,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "TECHNOLOGY",
            "asset_class_code": "TECHNOLOGY",
            "display_name": "Technology",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 114,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "SEMICONDUCTORS",
            "asset_class_code": "SEMICONDUCTORS",
            "display_name": "Semiconductors",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 116,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "INDUSTRIALS",
            "asset_class_code": "INDUSTRIALS",
            "display_name": "Industrials",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 118,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "DEFENCE",
            "asset_class_code": "DEFENCE",
            "display_name": "Defence",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 119,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "BONDS",
            "asset_class_code": "BONDS",
            "display_name": "Bonds",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 150,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "BROAD_EQUITY",
            "asset_class_code": "BROAD_EQUITY",
            "display_name": "Broad Equity",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1010,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "PHYSICAL_GOLD",
            "asset_class_code": "PHYSICAL_GOLD",
            "display_name": "Physical Gold",
            "class_type": "ALLOCATION",
            "parent_code": "GOLD",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1020,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "GOLD_MINERS",
            "asset_class_code": "GOLD",
            "display_name": "Gold Miners",
            "class_type": "ALLOCATION",
            "parent_code": "GOLD",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1025,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "PHYSICAL_SILVER",
            "asset_class_code": "PHYSICAL_SILVER",
            "display_name": "Physical Silver",
            "class_type": "ALLOCATION",
            "parent_code": "SILVER",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1030,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "SILVER_MINERS",
            "asset_class_code": "SILVER",
            "display_name": "Silver Miners",
            "class_type": "ALLOCATION",
            "parent_code": "SILVER",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1035,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "COPPER_MINERS",
            "asset_class_code": "COPPER",
            "display_name": "Copper Miners",
            "class_type": "ALLOCATION",
            "parent_code": "COPPER",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1040,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "BASE_METALS_MINERS",
            "asset_class_code": "BASEMETALS",
            "display_name": "Base Metals Miners",
            "class_type": "ALLOCATION",
            "parent_code": "BASEMETALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1045,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "LITHIUM_MINERS",
            "asset_class_code": "LITHIUM",
            "display_name": "Lithium Miners",
            "class_type": "ALLOCATION",
            "parent_code": "LITHIUM",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1050,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "URANIUM_MINERS",
            "asset_class_code": "URANIUM",
            "display_name": "Uranium Miners",
            "class_type": "ALLOCATION",
            "parent_code": "URANIUM",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1055,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "RARE_EARTHS_CRITICAL_MINERALS",
            "asset_class_code": "REE",
            "display_name": "Rare Earths \u0026 Critical Minerals",
            "class_type": "ALLOCATION",
            "parent_code": "REE",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1060,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "IRON_ORE_MINERS",
            "asset_class_code": "IRON",
            "display_name": "Iron Ore Miners",
            "class_type": "ALLOCATION",
            "parent_code": "IRON",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1065,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "DIVERSIFIED_MINERS",
            "asset_class_code": "MATERIALS",
            "display_name": "Diversified Miners",
            "class_type": "ALLOCATION",
            "parent_code": "MATERIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1070,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "MATERIALS_CHEMICALS",
            "asset_class_code": "MATERIALS_CHEMICALS",
            "display_name": "Materials \u0026 Chemicals",
            "class_type": "ALLOCATION",
            "parent_code": "MATERIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1075,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "FORESTRY_PAPER_PACKAGING",
            "asset_class_code": "FORESTRY_PAPER_PACKAGING",
            "display_name": "Forestry, Paper \u0026 Packaging",
            "class_type": "ALLOCATION",
            "parent_code": "MATERIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1080,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "STEEL_METALS_PROCESSING",
            "asset_class_code": "STEEL_METALS_PROCESSING",
            "display_name": "Steel \u0026 Metals Processing",
            "class_type": "ALLOCATION",
            "parent_code": "MATERIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1085,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "MINING_SERVICES",
            "asset_class_code": "MINING_SERVICES",
            "display_name": "Mining Services",
            "class_type": "ALLOCATION",
            "parent_code": "MATERIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1087,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "ENERGY_PRODUCERS",
            "asset_class_code": "ENERGY",
            "display_name": "Energy Producers",
            "class_type": "ALLOCATION",
            "parent_code": "ENERGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1090,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "ENERGY_COMMODITIES",
            "asset_class_code": "ENERGY_COMMODITIES",
            "display_name": "Energy Commodities",
            "class_type": "ALLOCATION",
            "parent_code": "ENERGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1095,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "AGRICULTURE_AGRIBUSINESS",
            "asset_class_code": "AGRICULTURE_AGRIBUSINESS",
            "display_name": "Agriculture \u0026 Agribusiness",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1100,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "BANKS",
            "asset_class_code": "BANKS",
            "display_name": "Banks",
            "class_type": "ALLOCATION",
            "parent_code": "FINANCIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1105,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "CONSUMER_STAPLES",
            "asset_class_code": "CONSUMER_STAPLES",
            "display_name": "Consumer Staples",
            "class_type": "ALLOCATION",
            "parent_code": "STAPLES",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1110,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "CONSUMER_DISCRETIONARY",
            "asset_class_code": "CONSUMER_DISCRETIONARY",
            "display_name": "Consumer Discretionary",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1115,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "GAMING_GAMBLING",
            "asset_class_code": "GAMING_GAMBLING",
            "display_name": "Gaming \u0026 Gambling",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1120,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "EDUCATION",
            "asset_class_code": "EDUCATION",
            "display_name": "Education",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1125,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "MEDIA_PUBLISHING",
            "asset_class_code": "MEDIA_PUBLISHING",
            "display_name": "Media \u0026 Publishing",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1130,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "TECHNOLOGY_PLATFORMS",
            "asset_class_code": "TECHNOLOGY_PLATFORMS",
            "display_name": "Technology Platforms",
            "class_type": "ALLOCATION",
            "parent_code": "TECHNOLOGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1135,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "SOFTWARE_SAAS",
            "asset_class_code": "SOFTWARE_SAAS",
            "display_name": "Software \u0026 SaaS",
            "class_type": "ALLOCATION",
            "parent_code": "TECHNOLOGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1140,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "CRYPTO_DIGITAL_ASSETS",
            "asset_class_code": "CRYPTO_DIGITAL_ASSETS",
            "display_name": "Crypto \u0026 Digital Assets",
            "class_type": "ALLOCATION",
            "parent_code": "TECHNOLOGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1145,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "DATACENTRES",
            "asset_class_code": "DATACENTRES",
            "display_name": "Datacentres",
            "class_type": "ALLOCATION",
            "parent_code": "TECHNOLOGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1150,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "TELECOMMUNICATIONS",
            "asset_class_code": "TELECOMMUNICATIONS",
            "display_name": "Telecommunications",
            "class_type": "ALLOCATION",
            "parent_code": "TECHNOLOGY",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1155,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "CONSTRUCTION_ENGINEERING",
            "asset_class_code": "CONSTRUCTION_ENGINEERING",
            "display_name": "Construction \u0026 Engineering",
            "class_type": "ALLOCATION",
            "parent_code": "INDUSTRIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1160,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "TRANSPORT_LOGISTICS",
            "asset_class_code": "TRANSPORT_LOGISTICS",
            "display_name": "Transport \u0026 Logistics",
            "class_type": "ALLOCATION",
            "parent_code": "INDUSTRIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1165,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "CIVIL_AEROSPACE",
            "asset_class_code": "CIVIL_AEROSPACE",
            "display_name": "Civil Aerospace",
            "class_type": "ALLOCATION",
            "parent_code": "INDUSTRIALS",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1170,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "INFRASTRUCTURE",
            "asset_class_code": "INFRASTRUCTURE",
            "display_name": "Infrastructure",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1175,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "UTILITIES",
            "asset_class_code": "UTILITIES",
            "display_name": "Utilities",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1180,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "REAL_ESTATE_REIT",
            "asset_class_code": "REAL_ESTATE_REIT",
            "display_name": "Real Estate / REIT",
            "class_type": "ALLOCATION",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1185,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "HEALTHCARE_SERVICES",
            "asset_class_code": "HEALTHCARE_SERVICES",
            "display_name": "Healthcare Services",
            "class_type": "ALLOCATION",
            "parent_code": "HEALTHCARE",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1190,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "MEDTECH",
            "asset_class_code": "MEDTECH",
            "display_name": "Medtech",
            "class_type": "ALLOCATION",
            "parent_code": "HEALTHCARE",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1195,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "PHARMA_BIOTECH",
            "asset_class_code": "PHARMA_BIOTECH",
            "display_name": "Pharma \u0026 Biotech",
            "class_type": "ALLOCATION",
            "parent_code": "PHARMA",
            "allow_grouping": true,
            "allow_target_weight": true,
            "analysis_eligible": true,
            "instrument_scope": "BOTH",
            "display_order": 1200,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "UNASSIGNED",
            "asset_class_code": "UNASSIGNED",
            "display_name": "Unassigned",
            "class_type": "SYSTEM_BUCKET",
            "allow_grouping": false,
            "allow_target_weight": true,
            "analysis_eligible": false,
            "instrument_scope": "BOTH",
            "display_order": 9990,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        },
        {
            "code": "CASH",
            "asset_class_code": "CASH",
            "display_name": "Cash/Reserve",
            "class_type": "SYSTEM_BUCKET",
            "allow_grouping": false,
            "allow_target_weight": true,
            "analysis_eligible": false,
            "instrument_scope": "BOTH",
            "risk_bucket": "CASH",
            "quartile": "CASH",
            "display_order": 10000,
            "active": true,
            "in_mandate": false,
            "mandate_weight_pct": 0
        }
    ],
    "config": [
        {
            "key": "MATERIALS",
            "display_name": "Materials",
            "alert_label": "Materials",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 10,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Broad materials remain equity-sensitive in drawdowns even when the underlying commodities are mixed.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "GOLD",
            "display_name": "Gold",
            "alert_label": "Gold",
            "alert_color": "#d4a017",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 20,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Gold miners retain inflation leverage but still carry equity beta, so they are not the same as physical gold.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "SILVER",
            "display_name": "Silver",
            "alert_label": "Silver",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 30,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Silver miners blend monetary upside with industrial cyclicality, which makes them noisier through drawdowns.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "COPPER",
            "display_name": "Copper",
            "alert_label": "Copper",
            "alert_color": "#b87333",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 40,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Copper can hold on supply stress, but copper equities still behave like cyclical risk assets in weaker markets.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "BASEMETALS",
            "display_name": "Base Metals",
            "alert_label": "Base Metals",
            "alert_color": "#c28b2c",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 50,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Base-metals names need case-by-case judgement because commodity support and equity beta often fight each other.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "LITHIUM",
            "display_name": "Lithium",
            "alert_label": "Lithium",
            "alert_color": "#a3e635",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 55,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Lithium remains tied to EV growth expectations and tends to behave poorly when risk appetite and growth assumptions compress.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "URANIUM",
            "display_name": "Uranium",
            "alert_label": "Uranium",
            "alert_color": "#84cc16",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 60,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Uranium has a strong long-term thesis, but listed uranium equities can still sell off with the broader equity book.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "REE",
            "display_name": "Rare Earths",
            "alert_label": "Rare Earths",
            "alert_color": "#22c55e",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 70,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Rare earths and critical-mineral explorers are often illiquid and highly equity-correlated when markets de-risk.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "IRON",
            "display_name": "Iron",
            "alert_label": "Iron",
            "alert_color": "#b45309",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 80,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Iron ore is heavily tied to cyclical demand, especially construction and China-sensitive growth expectations.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "ALUMINIUM",
            "display_name": "Aluminium",
            "alert_label": "Aluminium",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 90,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Aluminium can benefit from supply issues, but listed names still share the same broad equity drawdown risk.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "INSURANCE",
            "display_name": "Insurance",
            "alert_label": "Insurance",
            "alert_color": "#06b6d4",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 95,
            "q3_sell_priority": 5,
            "q3_throttle_factor": 0.5,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": true,
            "regime_independent": false,
            "q3_rating": "Strong",
            "q3_logic": "Premium repricing and higher portfolio yields make insurance one of the cleanest stagflation beneficiaries.",
            "stage2_target_pct": 25,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "FINANCIALS",
            "display_name": "Financials",
            "alert_label": "Financials",
            "alert_color": "#22d3ee",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 100,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Banks and broader financials can benefit from rates, but credit stress and provisioning offset that support.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "STAPLES",
            "display_name": "Staples",
            "alert_label": "Staples",
            "alert_color": "#84cc16",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 110,
            "q3_sell_priority": 5,
            "q3_throttle_factor": 0.5,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": true,
            "regime_independent": false,
            "q3_rating": "Strong",
            "q3_logic": "Staples have inelastic demand and better price pass-through than most of the equity book.",
            "stage2_target_pct": 15,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "GAMBLING",
            "display_name": "Gambling",
            "alert_label": "Gambling",
            "alert_color": "#d946ef",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 111,
            "q3_sell_priority": 5,
            "q3_throttle_factor": 0.5,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": true,
            "regime_independent": false,
            "q3_rating": "Good",
            "q3_logic": "Gambling behaves more defensively than most discretionary sectors and can stay resilient in stress.",
            "stage2_target_pct": 10,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "GAMING",
            "display_name": "Gaming",
            "alert_label": "Gaming",
            "alert_color": "#c084fc",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 112,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Gaming is more exposed to discretionary spending and should not be treated the same as gambling content.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "TECHNOLOGY",
            "display_name": "Technology",
            "alert_label": "Technology",
            "alert_color": "#38bdf8",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 114,
            "q3_sell_priority": 1,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Worst",
            "q3_logic": "Technology remains the most rate-sensitive, long-duration part of the equity book.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "SEMICONDUCTORS",
            "display_name": "Semiconductors",
            "alert_label": "Semis",
            "alert_color": "#60a5fa",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 116,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Semiconductors still carry cyclical demand and valuation compression risk in tougher regimes.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "INDUSTRIALS",
            "display_name": "Industrials",
            "alert_label": "Industrials",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 118,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Industrials face weaker demand, capex deferrals, and margin pressure when the market moves defensive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "DEFENCE",
            "display_name": "Defence",
            "alert_label": "Defence",
            "alert_color": "#ef4444",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 119,
            "q3_sell_priority": 5,
            "q3_throttle_factor": 0.5,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": true,
            "regime_independent": false,
            "q3_rating": "Good",
            "q3_logic": "Defence demand is supported by long-duration government budgets and a less cyclical demand backdrop.",
            "stage2_target_pct": 5,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "EQUITY",
            "display_name": "Equity",
            "alert_label": "Equity",
            "alert_color": "#94a3b8",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 120,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Generic equity exposure should be treated as overlay-sensitive unless it is reclassified into a more specific sleeve.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "ENERGY",
            "display_name": "Energy",
            "alert_label": "Energy",
            "alert_color": "#f97316",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": false,
            "display_order": 130,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Best",
            "q3_logic": "Energy producers benefit directly from the inflationary shock and sit outside the Q1 throttle.",
            "stage2_target_pct": 15,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "PHARMA",
            "display_name": "Pharma",
            "alert_label": "Pharma",
            "alert_color": "#10b981",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": false,
            "display_order": 140,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": true,
            "q3_rating": "Regime-Independent",
            "q3_logic": "Commercial pharma is driven by clinical demand and approvals, not by the Q1 overlay.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "HEALTHCARE",
            "display_name": "Healthcare",
            "alert_label": "Healthcare",
            "alert_color": "#14b8a6",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": false,
            "display_order": 145,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": true,
            "q3_rating": "Holds",
            "q3_logic": "Healthcare services and devices are less cyclical than the broad equity book and can hold through stress.",
            "stage2_target_pct": 5,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "BONDS",
            "display_name": "Bonds",
            "alert_label": "Bonds",
            "alert_color": "#a78bfa",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 150,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Nominal fixed income is not a clean Q3 beneficiary, but it remains outside the Q1 overlay when explicitly held.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "ETF",
            "display_name": "ETF Sleeve",
            "alert_label": "ETF",
            "alert_color": "#94a3b8",
            "kind": "SECURITY_TYPE",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": false,
            "display_order": 160,
            "q3_throttle_factor": 0,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "MISC",
            "display_name": "Misc",
            "alert_label": "Misc",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": true,
            "display_order": 170,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "UNASSIGNED",
            "display_name": "Unassigned",
            "alert_label": "Unassigned",
            "alert_color": "#9ca3af",
            "kind": "SYSTEM_BUCKET",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": false,
            "is_system_bucket": true,
            "allow_grouping": false,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 999,
            "q3_throttle_factor": 0,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "FIXED_INCOME",
            "display_name": "Fixed Income",
            "alert_label": "Bonds",
            "alert_color": "#a78bfa",
            "kind": "ASSET_CLASS",
            "is_portfolio_sleeve": false,
            "is_system_bucket": false,
            "allow_grouping": false,
            "allow_target_weight": false,
            "overlay_eligible": false,
            "display_order": 1005,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Fixed income is a portfolio target class rather than Q1 overlay equity exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "BROAD_EQUITY",
            "display_name": "Broad Equity",
            "alert_label": "Equity",
            "alert_color": "#94a3b8",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1010,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Broad equity exposure remains overlay-sensitive unless it is assigned to a more specific sleeve.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "PHYSICAL_GOLD",
            "display_name": "Physical Gold",
            "alert_label": "Gold",
            "alert_color": "#d4a017",
            "kind": "ASSET_CLASS",
            "parent_code": "GOLD",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1020,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Regime-Independent",
            "q3_logic": "Physical gold is treated separately from listed gold miners and sits outside Q1 equity reductions.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "GOLD_MINERS",
            "display_name": "Gold Miners",
            "alert_label": "Gold",
            "alert_color": "#d4a017",
            "kind": "ASSET_CLASS",
            "parent_code": "GOLD",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1025,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Listed gold miners carry equity beta even when bullion is defensive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "PHYSICAL_SILVER",
            "display_name": "Physical Silver",
            "alert_label": "Silver",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "parent_code": "SILVER",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1030,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Regime-Independent",
            "q3_logic": "Physical silver is treated separately from listed silver miners.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "SILVER_MINERS",
            "display_name": "Silver Miners",
            "alert_label": "Silver",
            "alert_color": "#9ca3af",
            "kind": "ASSET_CLASS",
            "parent_code": "SILVER",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1035,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Listed silver miners retain equity and cyclicality risk.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "COPPER_MINERS",
            "display_name": "Copper Miners",
            "alert_label": "Copper",
            "alert_color": "#b87333",
            "kind": "ASSET_CLASS",
            "parent_code": "COPPER",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1040,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Copper miners are cyclical listed equities and should not be conflated with physical copper exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "BASE_METALS_MINERS",
            "display_name": "Base Metals Miners",
            "alert_label": "Base Metals",
            "alert_color": "#c28b2c",
            "kind": "ASSET_CLASS",
            "parent_code": "BASEMETALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1045,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Base-metals miners need case-by-case treatment because commodity support and equity beta can conflict.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "LITHIUM_MINERS",
            "display_name": "Lithium Miners",
            "alert_label": "Lithium",
            "alert_color": "#a3e635",
            "kind": "ASSET_CLASS",
            "parent_code": "LITHIUM",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1050,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Lithium miners remain exposed to EV demand expectations and risk appetite.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "URANIUM_MINERS",
            "display_name": "Uranium Miners",
            "alert_label": "Uranium",
            "alert_color": "#84cc16",
            "kind": "ASSET_CLASS",
            "parent_code": "URANIUM",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1055,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Uranium miners have a strong long-term thesis but still carry listed-equity drawdown risk.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "RARE_EARTHS_CRITICAL_MINERALS",
            "display_name": "Rare Earths \u0026 Critical Minerals",
            "alert_label": "Rare Earths",
            "alert_color": "#22c55e",
            "kind": "ASSET_CLASS",
            "parent_code": "REE",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1060,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Critical-mineral equities are often illiquid and highly equity-correlated when markets de-risk.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "IRON_ORE_MINERS",
            "display_name": "Iron Ore Miners",
            "alert_label": "Iron",
            "alert_color": "#b45309",
            "kind": "ASSET_CLASS",
            "parent_code": "IRON",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1065,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Iron ore miners are exposed to cyclical demand and China-sensitive growth expectations.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "DIVERSIFIED_MINERS",
            "display_name": "Diversified Miners",
            "alert_label": "Diversified Miners",
            "alert_color": "#a16207",
            "kind": "ASSET_CLASS",
            "parent_code": "MATERIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1070,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Diversified miners blend multiple commodity drivers with listed-equity beta.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "MATERIALS_CHEMICALS",
            "display_name": "Materials \u0026 Chemicals",
            "alert_label": "Chemicals",
            "alert_color": "#2dd4bf",
            "kind": "ASSET_CLASS",
            "parent_code": "MATERIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1075,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Materials and chemicals are generally cyclical and overlay-sensitive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "FORESTRY_PAPER_PACKAGING",
            "display_name": "Forestry, Paper \u0026 Packaging",
            "alert_label": "Forestry",
            "alert_color": "#65a30d",
            "kind": "ASSET_CLASS",
            "parent_code": "MATERIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1080,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Packaging and forestry names mix industrial cyclicality with defensive end demand.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "STEEL_METALS_PROCESSING",
            "display_name": "Steel \u0026 Metals Processing",
            "alert_label": "Steel",
            "alert_color": "#94a3b8",
            "kind": "ASSET_CLASS",
            "parent_code": "MATERIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1085,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Steel and metals processing are cyclical and margin-sensitive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "MINING_SERVICES",
            "display_name": "Mining Services",
            "alert_label": "Mining Services",
            "alert_color": "#f59e0b",
            "kind": "ASSET_CLASS",
            "parent_code": "MATERIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1087,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Mining services are tied to mining activity, capex cycles, contract utilisation, and listed-equity risk.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "ENERGY_PRODUCERS",
            "display_name": "Energy Producers",
            "alert_label": "Energy",
            "alert_color": "#f97316",
            "kind": "ASSET_CLASS",
            "parent_code": "ENERGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1090,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Best",
            "q3_logic": "Energy producers benefit directly from inflationary shocks and are treated outside the Q1 throttle.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "ENERGY_COMMODITIES",
            "display_name": "Energy Commodities",
            "alert_label": "Commodities",
            "alert_color": "#fb923c",
            "kind": "ASSET_CLASS",
            "parent_code": "ENERGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1095,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Best",
            "q3_logic": "Direct energy commodity exposure is treated separately from Q1 overlay equities.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "AGRICULTURE_AGRIBUSINESS",
            "display_name": "Agriculture \u0026 Agribusiness",
            "alert_label": "Agriculture",
            "alert_color": "#84cc16",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1100,
            "q3_sell_priority": 4,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Good",
            "q3_logic": "Agriculture can have inflation pass-through but still needs listed-equity treatment.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "BANKS",
            "display_name": "Banks",
            "alert_label": "Banks",
            "alert_color": "#22d3ee",
            "kind": "ASSET_CLASS",
            "parent_code": "FINANCIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1105,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Banks can benefit from rates but are exposed to credit stress and provisioning.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "CONSUMER_STAPLES",
            "display_name": "Consumer Staples",
            "alert_label": "Staples",
            "alert_color": "#84cc16",
            "kind": "ASSET_CLASS",
            "parent_code": "STAPLES",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1110,
            "q3_sell_priority": 5,
            "q3_throttle_factor": 0.5,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": true,
            "regime_independent": false,
            "q3_rating": "Strong",
            "q3_logic": "Staples have inelastic demand and better price pass-through than most equities.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "CONSUMER_DISCRETIONARY",
            "display_name": "Consumer Discretionary",
            "alert_label": "Consumer",
            "alert_color": "#f59e0b",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1115,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Discretionary consumption is vulnerable when rates, inflation, or growth pressure households.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "GAMING_GAMBLING",
            "display_name": "Gaming \u0026 Gambling",
            "alert_label": "Gambling",
            "alert_color": "#d946ef",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1120,
            "q3_sell_priority": 4,
            "q3_throttle_factor": 0.5,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": true,
            "regime_independent": false,
            "q3_rating": "Good",
            "q3_logic": "Gaming and gambling exposure can be more resilient than discretionary retail but still needs equity-risk treatment.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "EDUCATION",
            "display_name": "Education",
            "alert_label": "Education",
            "alert_color": "#a78bfa",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1125,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Education demand can be resilient but listed names still carry equity beta.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "MEDIA_PUBLISHING",
            "display_name": "Media \u0026 Publishing",
            "alert_label": "Media",
            "alert_color": "#f472b6",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1130,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Advertising and publishing exposure is cyclical.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "TECHNOLOGY_PLATFORMS",
            "display_name": "Technology Platforms",
            "alert_label": "Platforms",
            "alert_color": "#38bdf8",
            "kind": "ASSET_CLASS",
            "parent_code": "TECHNOLOGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1135,
            "q3_sell_priority": 1,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Worst",
            "q3_logic": "Technology platforms remain rate-sensitive, long-duration equity exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "SOFTWARE_SAAS",
            "display_name": "Software \u0026 SaaS",
            "alert_label": "Software",
            "alert_color": "#0ea5e9",
            "kind": "ASSET_CLASS",
            "parent_code": "TECHNOLOGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1140,
            "q3_sell_priority": 1,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Worst",
            "q3_logic": "Software and SaaS valuations are sensitive to rates and growth compression.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "CRYPTO_DIGITAL_ASSETS",
            "display_name": "Crypto \u0026 Digital Assets",
            "alert_label": "Crypto",
            "alert_color": "#8b5cf6",
            "kind": "ASSET_CLASS",
            "parent_code": "TECHNOLOGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1145,
            "q3_sell_priority": 1,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Worst",
            "q3_logic": "Crypto and digital-asset exposure is high-beta risk exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "DATACENTRES",
            "display_name": "Datacentres",
            "alert_label": "Datacentres",
            "alert_color": "#60a5fa",
            "kind": "ASSET_CLASS",
            "parent_code": "TECHNOLOGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1150,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Datacentres have structural demand but are not the same as broad infrastructure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "TELECOMMUNICATIONS",
            "display_name": "Telecommunications",
            "alert_label": "Telecoms",
            "alert_color": "#22d3ee",
            "kind": "ASSET_CLASS",
            "parent_code": "TECHNOLOGY",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1155,
            "q3_sell_priority": 4,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Good",
            "q3_logic": "Telecommunications can be defensive but remains listed-equity exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "CONSTRUCTION_ENGINEERING",
            "display_name": "Construction \u0026 Engineering",
            "alert_label": "Construction",
            "alert_color": "#f97316",
            "kind": "ASSET_CLASS",
            "parent_code": "INDUSTRIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1160,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Construction and engineering are cyclical and capex-sensitive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "TRANSPORT_LOGISTICS",
            "display_name": "Transport \u0026 Logistics",
            "alert_label": "Transport",
            "alert_color": "#f59e0b",
            "kind": "ASSET_CLASS",
            "parent_code": "INDUSTRIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1165,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Transport and logistics exposure is cyclical and demand-sensitive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "CIVIL_AEROSPACE",
            "display_name": "Civil Aerospace",
            "alert_label": "Aerospace",
            "alert_color": "#60a5fa",
            "kind": "ASSET_CLASS",
            "parent_code": "INDUSTRIALS",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1170,
            "q3_sell_priority": 3,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Mixed",
            "q3_logic": "Civil aerospace has long-cycle demand but remains cyclical listed-equity exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "INFRASTRUCTURE",
            "display_name": "Infrastructure",
            "alert_label": "Infrastructure",
            "alert_color": "#64748b",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1175,
            "q3_throttle_factor": 0,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Holds",
            "q3_logic": "Infrastructure is separated from cyclical industrials and handled as a portfolio allocation sleeve.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "UTILITIES",
            "display_name": "Utilities",
            "alert_label": "Utilities",
            "alert_color": "#06b6d4",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1180,
            "q3_throttle_factor": 0,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Holds",
            "q3_logic": "Utilities are treated as defensive portfolio exposure outside the Q1 overlay.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "REAL_ESTATE_REIT",
            "display_name": "Real Estate / REIT",
            "alert_label": "REITs",
            "alert_color": "#a78bfa",
            "kind": "ASSET_CLASS",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": true,
            "display_order": 1185,
            "q3_sell_priority": 2,
            "q3_throttle_factor": 1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Bad",
            "q3_logic": "Real estate and REIT exposure is rate-sensitive.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "HEALTHCARE_SERVICES",
            "display_name": "Healthcare Services",
            "alert_label": "Healthcare",
            "alert_color": "#14b8a6",
            "kind": "ASSET_CLASS",
            "parent_code": "HEALTHCARE",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1190,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Holds",
            "q3_logic": "Healthcare services are less cyclical and sit outside the Q1 throttle when explicitly classified.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "MEDTECH",
            "display_name": "Medtech",
            "alert_label": "Medtech",
            "alert_color": "#2dd4bf",
            "kind": "ASSET_CLASS",
            "parent_code": "HEALTHCARE",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1195,
            "q3_throttle_factor": 0,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Holds",
            "q3_logic": "Medtech is separated from broad healthcare and handled as defensive healthcare exposure.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "PHARMA_BIOTECH",
            "display_name": "Pharma \u0026 Biotech",
            "alert_label": "Pharma",
            "alert_color": "#10b981",
            "kind": "ASSET_CLASS",
            "parent_code": "PHARMA",
            "is_portfolio_sleeve": true,
            "is_system_bucket": false,
            "allow_grouping": true,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 1200,
            "q3_throttle_factor": 0.1,
            "q4d_liquidity_factor": 1,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Regime-Independent",
            "q3_logic": "Pharma and biotech are driven by clinical demand and approvals rather than the Q1 overlay.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        },
        {
            "key": "CASH",
            "display_name": "Cash/Reserve",
            "alert_label": "Cash",
            "alert_color": "#9ca3af",
            "kind": "SYSTEM_BUCKET",
            "parent_code": "UNASSIGNED",
            "is_portfolio_sleeve": false,
            "is_system_bucket": true,
            "allow_grouping": false,
            "allow_target_weight": true,
            "overlay_eligible": false,
            "display_order": 10000,
            "q3_throttle_factor": 0,
            "q4d_liquidity_factor": 0,
            "q1_category": false,
            "q3_beneficiary": false,
            "regime_independent": false,
            "q3_rating": "Cash",
            "q3_logic": "Cash and reserve balances sit outside the Q1 overlay and fund the rebalance workflow.",
            "cash_reserve": 0,
            "stock_allocation_ratio": 0.75,
            "active": true
        }
    ]
};
