export type EnrichmentTemplate = {
  id: string;
  label: string;
  family: string;
  kind?: "retrieval_brief" | "copy_paste_prompt";
  category?: string;
  companyTypes?: string[];
  scoringFactors?: {
    quality?: string[];
    value?: string[];
  };
  assetClasses: string[];
  templateIds: string[];
  path: string;
  description: string;
};

const promptPath = (fileName: string) =>
  `/enrichment-prompts/manual/${fileName}`;

const copyPasteResearchPromptPath = (fileName: string) =>
  `/enrichment-prompts/copy-paste-research-prompts/${fileName}`;

const RETRIEVAL_ENRICHMENT_TEMPLATES: EnrichmentTemplate[] = [
  {
    id: "retrieval-agriculture-agribusiness",
    label: "Agriculture & Agribusiness Brief",
    family: "Brief / Agriculture",
    kind: "retrieval_brief",
    category: "agriculture",
    companyTypes: ["agriculture_agribusiness"],
    scoringFactors: {
      quality: ["Supply Chain Position", "Commodity/Crop Exposure", "Margin Resilience", "Working Capital Discipline", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "Asset/Network Value", "FCF Yield", "Cycle-Adjusted Multiple", "Strategic Value"],
    },
    assetClasses: ["AGRICULTURE"],
    templateIds: ["agriculture_agribusiness"],
    path: promptPath("agriculture-agribusiness.md"),
    description: "Stage 1 retrieval brief for Agriculture & Agribusiness.",
  },
  {
    id: "retrieval-asset-managers-diversified-financials",
    label: "Asset Managers & Diversified Financials Brief",
    family: "Brief / Financials",
    kind: "retrieval_brief",
    category: "financials",
    companyTypes: ["asset_managers_diversified_financials"],
    scoringFactors: {
      quality: ["Franchise/AUM Quality", "Flow Resilience", "Fee Durability", "Investment Performance", "Balance Sheet", "Governance"],
      value: ["Earnings Power vs Market Cap", "Fee-Related Earnings Multiple", "AUM/Platform Value", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["asset_managers_diversified_financials"],
    path: promptPath("asset-managers-diversified-financials.md"),
    description: "Stage 1 retrieval brief for Asset Managers & Diversified Financials.",
  },
  {
    id: "retrieval-bank-financials",
    label: "Bank Financials Brief",
    family: "Brief / Financials",
    kind: "retrieval_brief",
    category: "financials",
    companyTypes: ["bank_financials"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Franchise Quality", "Management", "Asset/Credit Quality", "Capital & Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "P/B vs ROE", "Earnings Power vs Price", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["bank_financials"],
    path: promptPath("bank-financials.md"),
    description: "Stage 1 retrieval brief for Bank Financials.",
  },
  {
    id: "retrieval-bauxite-miner",
    label: "Bauxite Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["bauxite_miner", "polymetallic_bauxite_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource tonne", "Expansion Upside", "Cost Competitiveness", "Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["bauxite_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Bauxite Miner.",
  },
  {
    id: "retrieval-base-metals-miner",
    label: "Base Metals Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["base_metals_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Resource/Reserve Quality", "Funding", "ESG"],
      value: ["Risked NAV vs Market Cap", "EV/Resource or EV/Reserve", "Expansion/Upside", "Cost Competitiveness", "Strategic Value"],
    },
    assetClasses: ["BASE_METALS_MINERS", "MATERIALS", "RESOURCES"],
    templateIds: ["base_metals_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Base Metals Miner.",
  },
  {
    id: "retrieval-chemicals-materials",
    label: "Chemicals & Materials Brief",
    family: "Brief / Materials",
    kind: "retrieval_brief",
    category: "materials",
    companyTypes: ["chemicals_materials"],
    scoringFactors: {
      quality: ["Cost Curve Position", "Product Mix Quality", "Pricing/Spread Resilience", "Asset Reliability", "Balance Sheet", "Governance"],
      value: ["Cycle-Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Asset Replacement Value", "Strategic Value"],
    },
    assetClasses: ["MATERIALS"],
    templateIds: ["chemicals_materials"],
    path: promptPath("chemicals-materials.md"),
    description: "Stage 1 retrieval brief for Chemicals & Materials.",
  },
  {
    id: "retrieval-civil-aerospace",
    label: "Civil Aerospace Brief",
    family: "Brief / Industrials",
    kind: "retrieval_brief",
    category: "industrials",
    companyTypes: ["civil_aerospace"],
    scoringFactors: {
      quality: ["Backlog/Program Quality", "Aftermarket Exposure", "Execution/Safety", "Supply Chain Resilience", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Installed Base/Aftermarket Value", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["civil_aerospace"],
    path: promptPath("civil-aerospace.md"),
    description: "Stage 1 retrieval brief for Civil Aerospace.",
  },
  {
    id: "retrieval-coal-miner",
    label: "Coal Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["coal_miner"],
    scoringFactors: {
      quality: ["Asset/Reserve Quality", "Cost Curve Position", "Market Access", "Management", "Funding/Balance Sheet", "ESG/Regulatory Risk"],
      value: ["NAV vs Market Cap", "EV/Reserve Tonne", "FCF Yield Through Cycle", "Cost Competitiveness", "Capital Return Capacity"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["coal_miner"],
    path: promptPath("coal-miner.md"),
    description: "Stage 1 retrieval brief for Coal Miner.",
  },
  {
    id: "retrieval-construction-engineering",
    label: "Construction & Engineering Brief",
    family: "Brief / Industrials",
    kind: "retrieval_brief",
    category: "industrials",
    companyTypes: ["construction_engineering"],
    scoringFactors: {
      quality: ["Backlog Quality", "Execution Discipline", "Contract Risk", "Cash Conversion", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "Backlog Margin Quality", "FCF Yield", "Asset/Development Value", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["construction_engineering"],
    path: promptPath("construction-engineering.md"),
    description: "Stage 1 retrieval brief for Construction & Engineering.",
  },
  {
    id: "retrieval-consumer-retail",
    label: "Consumer Retail Brief",
    family: "Brief / Equity",
    kind: "retrieval_brief",
    category: "equity",
    companyTypes: ["consumer_retail"],
    scoringFactors: {
      quality: ["Demand Resilience", "Brand/Channel Strength", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["consumer_retail"],
    path: promptPath("consumer-retail.md"),
    description: "Stage 1 retrieval brief for Consumer Retail.",
  },
  {
    id: "retrieval-consumer-staples",
    label: "Consumer Staples Brief",
    family: "Brief / Equity",
    kind: "retrieval_brief",
    category: "equity",
    companyTypes: ["consumer_staples"],
    scoringFactors: {
      quality: ["Demand Resilience", "Pricing Power", "Brand/Distribution Strength", "Management", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Margin Durability", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["consumer_staples"],
    path: promptPath("consumer-staples.md"),
    description: "Stage 1 retrieval brief for Consumer Staples.",
  },
  {
    id: "retrieval-copper-miner",
    label: "Copper Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["copper_miner", "polymetallic_copper_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource lb", "Expansion Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["copper_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Copper Miner.",
  },
  {
    id: "retrieval-crypto-digital-assets",
    label: "Crypto & Digital Assets Brief",
    family: "Brief / Technology",
    kind: "retrieval_brief",
    category: "technology",
    companyTypes: ["crypto_digital_assets"],
    scoringFactors: {
      quality: ["Regulatory/Compliance Position", "Platform/Infrastructure Quality", "Revenue Durability", "Balance Sheet/Treasury Risk", "Security/Operational Risk", "Governance"],
      value: ["Cycle-Normalized Earnings vs Market Cap", "Asset/Treasury Value", "FCF Yield", "Platform Optionality", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["crypto_digital_assets"],
    path: promptPath("crypto-digital-assets.md"),
    description: "Stage 1 retrieval brief for Crypto & Digital Assets.",
  },
  {
    id: "retrieval-datacentres",
    label: "Datacentres Brief",
    family: "Brief / Infrastructure",
    kind: "retrieval_brief",
    category: "infrastructure",
    companyTypes: ["datacentres"],
    scoringFactors: {
      quality: ["Power Access & Site Quality", "Lease Quality & Customer Mix", "Management", "Delivery Execution", "Balance Sheet/Funding", "Governance"],
      value: ["NAV vs Market Cap", "EV/Delivered MW", "FFO/FCF Yield", "Lease-up Optionality", "Strategic Value"],
    },
    assetClasses: ["INFRASTRUCTURE", "TECHNOLOGY", "INDUSTRIALS"],
    templateIds: ["datacentres"],
    path: promptPath("datacentres.md"),
    description: "Stage 1 retrieval brief for Datacentres.",
  },
  {
    id: "retrieval-defence",
    label: "Defence Brief",
    family: "Brief / Industrials",
    kind: "retrieval_brief",
    category: "industrials",
    companyTypes: ["defence"],
    scoringFactors: {
      quality: ["Contract Visibility", "Mission-Critical Positioning", "Management", "Programme Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Backlog Quality", "Margin Durability", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["defence"],
    path: promptPath("defence-aerospace.md"),
    description: "Stage 1 retrieval brief for Defence.",
  },
  {
    id: "retrieval-diversified-miner",
    label: "Diversified Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["diversified_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Portfolio Quality", "Funding", "ESG"],
      value: ["Risked NAV vs Market Cap", "EV/Resource Basket", "Portfolio Expansion Upside", "Cost Competitiveness", "Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["diversified_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Diversified Miner.",
  },
  {
    id: "retrieval-education",
    label: "Education Brief",
    family: "Brief / Consumer",
    kind: "retrieval_brief",
    category: "consumer",
    companyTypes: ["education"],
    scoringFactors: {
      quality: ["Brand/Outcome Quality", "Regulatory Position", "Student/Customer Economics", "Revenue Durability", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Platform/Brand Value", "Strategic Value"],
    },
    assetClasses: ["CONSUMER"],
    templateIds: ["education"],
    path: promptPath("education.md"),
    description: "Stage 1 retrieval brief for Education.",
  },
  {
    id: "retrieval-energy-oil-gas",
    label: "Energy (Oil/Gas) Brief",
    family: "Brief / Energy",
    kind: "retrieval_brief",
    category: "energy",
    companyTypes: ["energy_oil_gas"],
    scoringFactors: {
      quality: ["Jurisdiction", "Asset Quality", "Cost Position", "Management", "Funding/Balance Sheet"],
      value: ["NAV vs Market Cap", "EV/2P Reserves", "EV/Production", "FCF Yield at Strip", "Strategic Value"],
    },
    assetClasses: ["ENERGY"],
    templateIds: ["energy_oil_gas"],
    path: promptPath("energy-oil-gas.md"),
    description: "Stage 1 retrieval brief for Energy (Oil/Gas).",
  },
  {
    id: "retrieval-financials-bank-insurance",
    label: "Financials (Bank & Insurance) Brief",
    family: "Brief / Financials",
    kind: "retrieval_brief",
    category: "financials",
    companyTypes: ["bank_financials", "insurance"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Operating Franchise", "Management", "Risk Quality", "Capital & Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "P/B vs ROE", "Earnings Power vs Price", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["financials_bank_insurance"],
    path: promptPath("financials-bank-insurance.md"),
    description: "Stage 1 retrieval brief for Financials (Bank & Insurance).",
  },
  {
    id: "retrieval-fixed-income",
    label: "Fixed Income Brief",
    family: "Brief / Fixed Income",
    kind: "retrieval_brief",
    category: "fixed_income",
    companyTypes: ["fixed_income"],
    scoringFactors: {
      quality: ["Portfolio Credit Quality", "Duration/Rate Risk", "Management", "Income Stability", "Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Price", "Yield vs Risk", "Discount/Premium to NAV", "Distribution Sustainability", "Strategic Value"],
    },
    assetClasses: ["BONDS"],
    templateIds: ["fixed_income"],
    path: promptPath("fixed-income-credit.md"),
    description: "Stage 1 retrieval brief for Fixed Income.",
  },
  {
    id: "retrieval-forestry-paper-packaging",
    label: "Forestry, Paper & Packaging Brief",
    family: "Brief / Materials",
    kind: "retrieval_brief",
    category: "materials",
    companyTypes: ["forestry_paper_packaging"],
    scoringFactors: {
      quality: ["Fibre/Asset Quality", "Packaging Franchise Quality", "Margin Resilience", "Sustainability/Regulatory Position", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Timberland/Asset Value", "Strategic Value"],
    },
    assetClasses: ["MATERIALS"],
    templateIds: ["forestry_paper_packaging"],
    path: promptPath("forestry-paper-packaging.md"),
    description: "Stage 1 retrieval brief for Forestry, Paper & Packaging.",
  },
  {
    id: "retrieval-gambling",
    label: "Gambling Brief",
    family: "Brief / Equity",
    kind: "retrieval_brief",
    category: "equity",
    companyTypes: ["gambling"],
    scoringFactors: {
      quality: ["Regulatory Position", "Product/Distribution Quality", "Management", "Revenue Resilience", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Recurring Revenue Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["gambling"],
    path: promptPath("gambling-wagering.md"),
    description: "Stage 1 retrieval brief for Gambling.",
  },
  {
    id: "retrieval-gaming-interactive",
    label: "Gaming Interactive Brief",
    family: "Brief / Technology",
    kind: "retrieval_brief",
    category: "technology",
    companyTypes: ["gaming_interactive"],
    scoringFactors: {
      quality: ["Franchise/IP Strength", "Retention & Live Ops", "Management", "Monetisation Quality", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Bookings vs Growth", "Cash Conversion", "Release Slate Optionality", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["gaming_interactive"],
    path: promptPath("gaming-interactive.md"),
    description: "Stage 1 retrieval brief for Gaming Interactive.",
  },
  {
    id: "retrieval-general-equity",
    label: "General Equity Brief",
    family: "Brief / General",
    kind: "retrieval_brief",
    category: "general",
    companyTypes: ["general_equity"],
    scoringFactors: {
      quality: ["Market Position", "Operating Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Cash-Flow Yield", "Relative Multiple", "Growth Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY", "ETF", "MISC", "UNASSIGNED"],
    templateIds: ["general_equity"],
    path: promptPath("general-equity.md"),
    description: "Stage 1 retrieval brief for General Equity.",
  },
  {
    id: "retrieval-gold-miner",
    label: "Gold Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["gold_miner", "polymetallic_gold_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource oz", "Exploration Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["gold_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Gold Miner.",
  },
  {
    id: "retrieval-healthcare-services",
    label: "Healthcare Services Brief",
    family: "Brief / Healthcare",
    kind: "retrieval_brief",
    category: "healthcare",
    companyTypes: ["healthcare_services"],
    scoringFactors: {
      quality: ["Demand Inelasticity", "Reimbursement/Contract Quality", "Management", "Operating Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Utilization Upside", "Strategic Value"],
    },
    assetClasses: ["HEALTHCARE"],
    templateIds: ["healthcare_services"],
    path: promptPath("healthcare-services.md"),
    description: "Stage 1 retrieval brief for Healthcare Services.",
  },
  {
    id: "retrieval-industrials",
    label: "Industrials Brief",
    family: "Brief / Equity",
    kind: "retrieval_brief",
    category: "equity",
    companyTypes: ["industrials"],
    scoringFactors: {
      quality: ["Demand Resilience", "Asset/Operating Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["industrials"],
    path: promptPath("industrials.md"),
    description: "Stage 1 retrieval brief for Industrials.",
  },
  {
    id: "retrieval-infrastructure",
    label: "Infrastructure Brief",
    family: "Brief / Infrastructure",
    kind: "retrieval_brief",
    category: "infrastructure",
    companyTypes: ["infrastructure"],
    scoringFactors: {
      quality: ["Asset Essentiality", "Contract/Regulatory Quality", "Cash Conversion", "Balance Sheet", "Management", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "FCF/Distribution Yield", "EV/EBITDA or RAB Multiple", "Growth/Capex Pipeline", "Strategic Value"],
    },
    assetClasses: ["INFRASTRUCTURE"],
    templateIds: ["infrastructure"],
    path: promptPath("infrastructure.md"),
    description: "Stage 1 retrieval brief for Infrastructure.",
  },
  {
    id: "retrieval-industrials-consumer-reit",
    label: "Industrials / Consumer / REIT Brief",
    family: "Brief / Equity",
    kind: "retrieval_brief",
    category: "equity",
    companyTypes: ["industrials", "consumer_retail", "real_estate_reit"],
    scoringFactors: {
      quality: ["Demand Resilience", "Asset/Operating Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["industrials_consumer_reit"],
    path: promptPath("industrials-consumer-reit.md"),
    description: "Stage 1 retrieval brief for Industrials / Consumer / REIT.",
  },
  {
    id: "retrieval-insurance",
    label: "Insurance Brief",
    family: "Brief / Financials",
    kind: "retrieval_brief",
    category: "financials",
    companyTypes: ["insurance"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Underwriting Quality", "Management", "Reserve Adequacy", "Capital & Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "P/B vs ROE", "Earnings Power vs Price", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["insurance"],
    path: promptPath("insurance.md"),
    description: "Stage 1 retrieval brief for Insurance.",
  },
  {
    id: "retrieval-iron-ore-miner",
    label: "Iron Ore Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["iron_ore_miner"],
    scoringFactors: {
      quality: ["Jurisdiction/Infrastructure", "Resource/Reserve Quality", "Cost Curve Position", "Management", "Funding/Balance Sheet", "ESG/Permitting"],
      value: ["NAV vs Market Cap", "EV/Reserve or Resource Tonne", "Cost Competitiveness", "Expansion Optionality", "Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["iron_ore_miner"],
    path: promptPath("iron-ore-miner.md"),
    description: "Stage 1 retrieval brief for Iron Ore Miner.",
  },
  {
    id: "retrieval-lithium-miner",
    label: "Lithium Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["lithium_miner", "polymetallic_lithium_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource t LCE", "Expansion Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["lithium_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Lithium Miner.",
  },
  {
    id: "retrieval-mining-services",
    label: "Mining Services Brief",
    family: "Brief / Industrials",
    kind: "retrieval_brief",
    category: "industrials",
    companyTypes: ["mining_services"],
    scoringFactors: {
      quality: ["Revenue Visibility", "Contract Quality", "Utilisation and Execution", "Cash Conversion", "Balance Sheet", "Customer and Commodity Diversification"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Cycle and Peers", "FCF Yield", "Fleet/Asset Replacement Value", "Strategic Value"],
    },
    assetClasses: ["MINING_SERVICES", "INDUSTRIALS", "MATERIALS"],
    templateIds: ["mining_services"],
    path: promptPath("mining-services.md"),
    description: "Stage 1 retrieval brief for Mining Services.",
  },
  {
    id: "retrieval-media-publishing",
    label: "Media & Publishing Brief",
    family: "Brief / Media",
    kind: "retrieval_brief",
    category: "media",
    companyTypes: ["media_publishing"],
    scoringFactors: {
      quality: ["Audience/Brand Quality", "Revenue Mix Durability", "Cost Discipline", "Digital Transition", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Subscriber/Audience Value", "Strategic Value"],
    },
    assetClasses: ["MEDIA"],
    templateIds: ["media_publishing"],
    path: promptPath("media-publishing.md"),
    description: "Stage 1 retrieval brief for Media & Publishing.",
  },
  {
    id: "retrieval-medtech",
    label: "Medtech Brief",
    family: "Brief / Healthcare",
    kind: "retrieval_brief",
    category: "healthcare",
    companyTypes: ["medtech"],
    scoringFactors: {
      quality: ["Regulatory & Quality Systems", "Clinical/Technical Evidence", "Management", "Commercial Execution", "Cash Runway/Funding", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Sales vs Growth", "Gross Margin & Cash Conversion", "Adoption Curve Optionality", "Strategic Value"],
    },
    assetClasses: ["HEALTHCARE"],
    templateIds: ["medtech"],
    path: promptPath("medtech.md"),
    description: "Stage 1 retrieval brief for Medtech.",
  },
  {
    id: "retrieval-pharma-biotech",
    label: "Pharmaceutical & Biotech Brief",
    family: "Brief / Pharma",
    kind: "retrieval_brief",
    category: "pharma",
    companyTypes: ["pharma_biotech", "medtech"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Scientific & Manufacturing Capability", "Management", "Pipeline Maturity", "Cash Runway/Funding", "Clinical & Ethical Standards"],
      value: ["rNPV vs Market Cap", "EV / Risk-Adjusted Peak Sales", "Pipeline Optionality", "Competitive Position", "Strategic Value"],
    },
    assetClasses: ["PHARMA", "HEALTHCARE"],
    templateIds: ["pharma_biotech"],
    path: promptPath("pharma-biotech.md"),
    description: "Stage 1 retrieval brief for Pharmaceutical & Biotech.",
  },
  {
    id: "retrieval-rare-earths-critical-minerals",
    label: "Rare Earths & Critical Minerals Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["rare_earths_critical_minerals"],
    scoringFactors: {
      quality: ["Resource/Processing Quality", "Strategic Supply Chain Position", "Permitting/Jurisdiction", "Management", "Funding/Balance Sheet", "ESG"],
      value: ["Risked NAV vs Market Cap", "EV/Resource Unit", "Separation/Processing Optionality", "Strategic/Policy Value", "Offtake/Funding Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["rare_earths_critical_minerals"],
    path: promptPath("rare-earths-critical-minerals.md"),
    description: "Stage 1 retrieval brief for Rare Earths & Critical Minerals.",
  },
  {
    id: "retrieval-real-estate-reit",
    label: "Real Estate / REIT Brief",
    family: "Brief / Equity",
    kind: "retrieval_brief",
    category: "equity",
    companyTypes: ["real_estate_reit"],
    scoringFactors: {
      quality: ["Asset Quality", "Occupancy & Lease Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["NAV vs Market Cap", "FFO/AFFO Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["real_estate_reit"],
    path: promptPath("real-estate-reit.md"),
    description: "Stage 1 retrieval brief for Real Estate / REIT.",
  },
  {
    id: "retrieval-semiconductors",
    label: "Semiconductors Brief",
    family: "Brief / Technology",
    kind: "retrieval_brief",
    category: "technology",
    companyTypes: ["semiconductors"],
    scoringFactors: {
      quality: ["Technology/IP Position", "End-Market Quality", "Management", "Cycle Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Cycle-Normal Earnings Power", "Multiple vs Peers", "Margin Resilience", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["semiconductors"],
    path: promptPath("semiconductors.md"),
    description: "Stage 1 retrieval brief for Semiconductors.",
  },
  {
    id: "retrieval-silver-miner",
    label: "Silver Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["silver_miner", "polymetallic_silver_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource oz", "Exploration Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["silver_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Silver Miner.",
  },
  {
    id: "retrieval-software-saas",
    label: "Software & SaaS Brief",
    family: "Brief / Technology",
    kind: "retrieval_brief",
    category: "technology",
    companyTypes: ["software_saas"],
    scoringFactors: {
      quality: ["Market & Demand Quality", "Product Moat", "Management", "Growth Quality", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Sales vs Growth", "Rule of 40 & Margin Path", "Retention Economics", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["software_saas"],
    path: promptPath("software-saas.md"),
    description: "Stage 1 retrieval brief for Software & SaaS.",
  },
  {
    id: "retrieval-steel-base-metals-processing",
    label: "Steel & Base Metals Processing Brief",
    family: "Brief / Materials",
    kind: "retrieval_brief",
    category: "materials",
    companyTypes: ["steel_base_metals_processing"],
    scoringFactors: {
      quality: ["Cost Curve Position", "Asset/Plant Quality", "End-Market Exposure", "Cash Conversion", "Balance Sheet", "Governance"],
      value: ["Cycle-Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Replacement/Asset Value", "Strategic Value"],
    },
    assetClasses: ["MATERIALS"],
    templateIds: ["steel_base_metals_processing"],
    path: promptPath("steel-base-metals-processing.md"),
    description: "Stage 1 retrieval brief for Steel & Base Metals Processing.",
  },
  {
    id: "retrieval-technology-platforms",
    label: "Technology Platforms Brief",
    family: "Brief / Technology",
    kind: "retrieval_brief",
    category: "technology",
    companyTypes: ["technology_platforms"],
    scoringFactors: {
      quality: ["Platform/Product Moat", "Retention & Network Effects", "Management", "Growth Quality", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Sales vs Growth", "Margin Path", "Unit Economics", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["technology_platforms"],
    path: promptPath("technology-platforms.md"),
    description: "Stage 1 retrieval brief for Technology Platforms.",
  },
  {
    id: "retrieval-telecommunications",
    label: "Telecommunications Brief",
    family: "Brief / Telecommunications",
    kind: "retrieval_brief",
    category: "telecommunications",
    companyTypes: ["telecommunications"],
    scoringFactors: {
      quality: ["Network Quality", "Subscriber Economics", "Pricing Power", "Capital Intensity", "Balance Sheet", "Governance"],
      value: ["DCF/FCF vs Market Cap", "EV/EBITDA vs Peers", "Dividend Capacity", "Infrastructure Optionality", "Strategic Value"],
    },
    assetClasses: ["TELECOMMUNICATIONS"],
    templateIds: ["telecommunications"],
    path: promptPath("telecommunications.md"),
    description: "Stage 1 retrieval brief for Telecommunications.",
  },
  {
    id: "retrieval-transport-logistics",
    label: "Transport & Logistics Brief",
    family: "Brief / Industrials",
    kind: "retrieval_brief",
    category: "industrials",
    companyTypes: ["transport_logistics"],
    scoringFactors: {
      quality: ["Route/Network Quality", "Cycle Resilience", "Cost Control", "Asset Utilization", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Asset/Network Value", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["transport_logistics"],
    path: promptPath("transport-logistics.md"),
    description: "Stage 1 retrieval brief for Transport & Logistics.",
  },
  {
    id: "retrieval-uranium-miner",
    label: "Uranium Miner Brief",
    family: "Brief / Resources",
    kind: "retrieval_brief",
    category: "resources",
    companyTypes: ["uranium_miner", "polymetallic_uranium_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource lb U3O8", "Exploration Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["MATERIALS", "RESOURCES"],
    templateIds: ["uranium_miner"],
    path: promptPath("resources-mining.md"),
    description: "Stage 1 retrieval brief for Uranium Miner.",
  },
  {
    id: "retrieval-utilities",
    label: "Utilities Brief",
    family: "Brief / Utilities",
    kind: "retrieval_brief",
    category: "utilities",
    companyTypes: ["utilities"],
    scoringFactors: {
      quality: ["Regulatory Framework", "Asset Base Quality", "Earnings Resilience", "Capital Structure", "Execution", "Governance"],
      value: ["Regulated Asset Value vs Market Cap", "Dividend/FCF Support", "Allowed Return vs WACC", "Growth Capex Quality", "Strategic Infrastructure Value"],
    },
    assetClasses: ["UTILITIES"],
    templateIds: ["utilities"],
    path: promptPath("utilities.md"),
    description: "Stage 1 retrieval brief for Utilities.",
  },
];


const COPY_PASTE_RESEARCH_PROMPT_TEMPLATES: EnrichmentTemplate[] = [
  {
    id: "copy-paste-research-agriculture-agribusiness",
    label: "Agriculture & Agribusiness Prompt",
    family: "Prompt / Agriculture",
    kind: "copy_paste_prompt",
    category: "agriculture",
    companyTypes: ["agriculture_agribusiness"],
    scoringFactors: {
      quality: ["Supply Chain Position", "Commodity/Crop Exposure", "Margin Resilience", "Working Capital Discipline", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "Asset/Network Value", "FCF Yield", "Cycle-Adjusted Multiple", "Strategic Value"],
    },
    assetClasses: ["AGRICULTURE"],
    templateIds: ["agriculture_agribusiness"],
    path: copyPasteResearchPromptPath("agriculture_agribusiness.yaml"),
    description: "Manual Web UI copy/paste research prompt for Agriculture & Agribusiness.",
  },
  {
    id: "copy-paste-research-asset-managers-diversified-financials",
    label: "Asset Managers & Diversified Financials Prompt",
    family: "Prompt / Financials",
    kind: "copy_paste_prompt",
    category: "financials",
    companyTypes: ["asset_managers_diversified_financials"],
    scoringFactors: {
      quality: ["Franchise/AUM Quality", "Flow Resilience", "Fee Durability", "Investment Performance", "Balance Sheet", "Governance"],
      value: ["Earnings Power vs Market Cap", "Fee-Related Earnings Multiple", "AUM/Platform Value", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["asset_managers_diversified_financials"],
    path: copyPasteResearchPromptPath("asset_managers_diversified_financials.yaml"),
    description: "Manual Web UI copy/paste research prompt for Asset Managers & Diversified Financials.",
  },
  {
    id: "copy-paste-research-bank-financials",
    label: "Bank Financials Prompt",
    family: "Prompt / Financials",
    kind: "copy_paste_prompt",
    category: "financials",
    companyTypes: ["bank_financials"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Franchise Quality", "Management", "Asset/Credit Quality", "Capital & Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "P/B vs ROE", "Earnings Power vs Price", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["bank_financials"],
    path: copyPasteResearchPromptPath("bank_financials.yaml"),
    description: "Manual Web UI copy/paste research prompt for Bank Financials.",
  },
  {
    id: "copy-paste-research-bauxite-miner",
    label: "Bauxite Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["bauxite_miner", "polymetallic_bauxite_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource tonne", "Expansion Upside", "Cost Competitiveness", "Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["bauxite_miner"],
    path: copyPasteResearchPromptPath("bauxite_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Bauxite Miner.",
  },
  {
    id: "copy-paste-research-chemicals-materials",
    label: "Chemicals & Materials Prompt",
    family: "Prompt / Materials",
    kind: "copy_paste_prompt",
    category: "materials",
    companyTypes: ["chemicals_materials"],
    scoringFactors: {
      quality: ["Cost Curve Position", "Product Mix Quality", "Pricing/Spread Resilience", "Asset Reliability", "Balance Sheet", "Governance"],
      value: ["Cycle-Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Asset Replacement Value", "Strategic Value"],
    },
    assetClasses: ["MATERIALS"],
    templateIds: ["chemicals_materials"],
    path: copyPasteResearchPromptPath("chemicals_materials.yaml"),
    description: "Manual Web UI copy/paste research prompt for Chemicals & Materials.",
  },
  {
    id: "copy-paste-research-civil-aerospace",
    label: "Civil Aerospace Prompt",
    family: "Prompt / Industrials",
    kind: "copy_paste_prompt",
    category: "industrials",
    companyTypes: ["civil_aerospace"],
    scoringFactors: {
      quality: ["Backlog/Program Quality", "Aftermarket Exposure", "Execution/Safety", "Supply Chain Resilience", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Installed Base/Aftermarket Value", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["civil_aerospace"],
    path: copyPasteResearchPromptPath("civil_aerospace.yaml"),
    description: "Manual Web UI copy/paste research prompt for Civil Aerospace.",
  },
  {
    id: "copy-paste-research-coal-miner",
    label: "Coal Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["coal_miner"],
    scoringFactors: {
      quality: ["Asset/Reserve Quality", "Cost Curve Position", "Market Access", "Management", "Funding/Balance Sheet", "ESG/Regulatory Risk"],
      value: ["NAV vs Market Cap", "EV/Reserve Tonne", "FCF Yield Through Cycle", "Cost Competitiveness", "Capital Return Capacity"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["coal_miner"],
    path: copyPasteResearchPromptPath("coal_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Coal Miner.",
  },
  {
    id: "copy-paste-research-base-metals-miner",
    label: "Base Metals Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["base_metals_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Resource/Reserve Quality", "Funding", "ESG"],
      value: ["Risked NAV vs Market Cap", "EV/Resource or EV/Reserve", "Expansion/Upside", "Cost Competitiveness", "Strategic Value"],
    },
    assetClasses: ["BASE_METALS_MINERS", "RESOURCES"],
    templateIds: ["base_metals_miner"],
    path: copyPasteResearchPromptPath("base_metals_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Base Metals Miner.",
  },
  {
    id: "copy-paste-research-construction-engineering",
    label: "Construction & Engineering Prompt",
    family: "Prompt / Industrials",
    kind: "copy_paste_prompt",
    category: "industrials",
    companyTypes: ["construction_engineering"],
    scoringFactors: {
      quality: ["Backlog Quality", "Execution Discipline", "Contract Risk", "Cash Conversion", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "Backlog Margin Quality", "FCF Yield", "Asset/Development Value", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["construction_engineering"],
    path: copyPasteResearchPromptPath("construction_engineering.yaml"),
    description: "Manual Web UI copy/paste research prompt for Construction & Engineering.",
  },
  {
    id: "copy-paste-research-infrastructure",
    label: "Infrastructure Prompt",
    family: "Prompt / Infrastructure",
    kind: "copy_paste_prompt",
    category: "infrastructure",
    companyTypes: ["infrastructure"],
    scoringFactors: {
      quality: ["Asset Essentiality", "Contract/Regulatory Quality", "Cash Conversion", "Balance Sheet", "Management", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "FCF/Distribution Yield", "EV/EBITDA or RAB Multiple", "Growth/Capex Pipeline", "Strategic Value"],
    },
    assetClasses: ["INFRASTRUCTURE"],
    templateIds: ["infrastructure"],
    path: copyPasteResearchPromptPath("infrastructure.yaml"),
    description: "Manual Web UI copy/paste research prompt for Infrastructure.",
  },
  {
    id: "copy-paste-research-consumer-retail",
    label: "Consumer Retail Prompt",
    family: "Prompt / Equity",
    kind: "copy_paste_prompt",
    category: "equity",
    companyTypes: ["consumer_retail"],
    scoringFactors: {
      quality: ["Demand Resilience", "Brand/Channel Strength", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["consumer_retail"],
    path: copyPasteResearchPromptPath("consumer_retail.yaml"),
    description: "Manual Web UI copy/paste research prompt for Consumer Retail.",
  },
  {
    id: "copy-paste-research-consumer-staples",
    label: "Consumer Staples Prompt",
    family: "Prompt / Equity",
    kind: "copy_paste_prompt",
    category: "equity",
    companyTypes: ["consumer_staples"],
    scoringFactors: {
      quality: ["Demand Resilience", "Pricing Power", "Brand/Distribution Strength", "Management", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Margin Durability", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["consumer_staples"],
    path: copyPasteResearchPromptPath("consumer_staples.yaml"),
    description: "Manual Web UI copy/paste research prompt for Consumer Staples.",
  },
  {
    id: "copy-paste-research-copper-miner",
    label: "Copper Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["copper_miner", "polymetallic_copper_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource lb", "Expansion Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["copper_miner"],
    path: copyPasteResearchPromptPath("copper_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Copper Miner.",
  },
  {
    id: "copy-paste-research-crypto-digital-assets",
    label: "Crypto & Digital Assets Prompt",
    family: "Prompt / Technology",
    kind: "copy_paste_prompt",
    category: "technology",
    companyTypes: ["crypto_digital_assets"],
    scoringFactors: {
      quality: ["Regulatory/Compliance Position", "Platform/Infrastructure Quality", "Revenue Durability", "Balance Sheet/Treasury Risk", "Security/Operational Risk", "Governance"],
      value: ["Cycle-Normalized Earnings vs Market Cap", "Asset/Treasury Value", "FCF Yield", "Platform Optionality", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["crypto_digital_assets"],
    path: copyPasteResearchPromptPath("crypto_digital_assets.yaml"),
    description: "Manual Web UI copy/paste research prompt for Crypto & Digital Assets.",
  },
  {
    id: "copy-paste-research-datacentres",
    label: "Datacentres Prompt",
    family: "Prompt / Infrastructure",
    kind: "copy_paste_prompt",
    category: "infrastructure",
    companyTypes: ["datacentres"],
    scoringFactors: {
      quality: ["Power Access & Site Quality", "Lease Quality & Customer Mix", "Management", "Delivery Execution", "Balance Sheet/Funding", "Governance"],
      value: ["NAV vs Market Cap", "EV/Delivered MW", "FFO/FCF Yield", "Lease-up Optionality", "Strategic Value"],
    },
    assetClasses: ["INFRASTRUCTURE"],
    templateIds: ["datacentres"],
    path: copyPasteResearchPromptPath("datacentres.yaml"),
    description: "Manual Web UI copy/paste research prompt for Datacentres.",
  },
  {
    id: "copy-paste-research-defence",
    label: "Defence Prompt",
    family: "Prompt / Industrials",
    kind: "copy_paste_prompt",
    category: "industrials",
    companyTypes: ["defence"],
    scoringFactors: {
      quality: ["Contract Visibility", "Mission-Critical Positioning", "Management", "Programme Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Backlog Quality", "Margin Durability", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["defence"],
    path: copyPasteResearchPromptPath("defence.yaml"),
    description: "Manual Web UI copy/paste research prompt for Defence.",
  },
  {
    id: "copy-paste-research-diversified-miner",
    label: "Diversified Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["diversified_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Portfolio Quality", "Funding", "ESG"],
      value: ["Risked NAV vs Market Cap", "EV/Resource Basket", "Portfolio Expansion Upside", "Cost Competitiveness", "Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["diversified_miner"],
    path: copyPasteResearchPromptPath("diversified_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Diversified Miner.",
  },
  {
    id: "copy-paste-research-education",
    label: "Education Prompt",
    family: "Prompt / Consumer",
    kind: "copy_paste_prompt",
    category: "consumer",
    companyTypes: ["education"],
    scoringFactors: {
      quality: ["Brand/Outcome Quality", "Regulatory Position", "Student/Customer Economics", "Revenue Durability", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Platform/Brand Value", "Strategic Value"],
    },
    assetClasses: ["CONSUMER"],
    templateIds: ["education"],
    path: copyPasteResearchPromptPath("education.yaml"),
    description: "Manual Web UI copy/paste research prompt for Education.",
  },
  {
    id: "copy-paste-research-energy-oil-gas",
    label: "Energy (Oil/Gas) Prompt",
    family: "Prompt / Energy",
    kind: "copy_paste_prompt",
    category: "energy",
    companyTypes: ["energy_oil_gas"],
    scoringFactors: {
      quality: ["Jurisdiction", "Asset Quality", "Cost Position", "Management", "Funding/Balance Sheet"],
      value: ["NAV vs Market Cap", "EV/2P Reserves", "EV/Production", "FCF Yield at Strip", "Strategic Value"],
    },
    assetClasses: ["ENERGY"],
    templateIds: ["energy_oil_gas"],
    path: copyPasteResearchPromptPath("energy_oil_gas.yaml"),
    description: "Manual Web UI copy/paste research prompt for Energy (Oil/Gas).",
  },
  {
    id: "copy-paste-research-financials-bank-insurance",
    label: "Financials (Bank & Insurance) Prompt",
    family: "Prompt / Financials",
    kind: "copy_paste_prompt",
    category: "financials",
    companyTypes: ["bank_financials", "insurance"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Operating Franchise", "Management", "Risk Quality", "Capital & Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "P/B vs ROE", "Earnings Power vs Price", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["financials_bank_insurance"],
    path: copyPasteResearchPromptPath("financials_bank_insurance.yaml"),
    description: "Manual Web UI copy/paste research prompt for Financials (Bank & Insurance).",
  },
  {
    id: "copy-paste-research-fixed-income",
    label: "Fixed Income Prompt",
    family: "Prompt / Fixed Income",
    kind: "copy_paste_prompt",
    category: "fixed_income",
    companyTypes: ["fixed_income"],
    scoringFactors: {
      quality: ["Portfolio Credit Quality", "Duration/Rate Risk", "Management", "Income Stability", "Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Price", "Yield vs Risk", "Discount/Premium to NAV", "Distribution Sustainability", "Strategic Value"],
    },
    assetClasses: ["FIXED_INCOME"],
    templateIds: ["fixed_income"],
    path: copyPasteResearchPromptPath("fixed_income.yaml"),
    description: "Manual Web UI copy/paste research prompt for Fixed Income.",
  },
  {
    id: "copy-paste-research-forestry-paper-packaging",
    label: "Forestry, Paper & Packaging Prompt",
    family: "Prompt / Materials",
    kind: "copy_paste_prompt",
    category: "materials",
    companyTypes: ["forestry_paper_packaging"],
    scoringFactors: {
      quality: ["Fibre/Asset Quality", "Packaging Franchise Quality", "Margin Resilience", "Sustainability/Regulatory Position", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Timberland/Asset Value", "Strategic Value"],
    },
    assetClasses: ["MATERIALS"],
    templateIds: ["forestry_paper_packaging"],
    path: copyPasteResearchPromptPath("forestry_paper_packaging.yaml"),
    description: "Manual Web UI copy/paste research prompt for Forestry, Paper & Packaging.",
  },
  {
    id: "copy-paste-research-gambling",
    label: "Gambling Prompt",
    family: "Prompt / Equity",
    kind: "copy_paste_prompt",
    category: "equity",
    companyTypes: ["gambling"],
    scoringFactors: {
      quality: ["Regulatory Position", "Product/Distribution Quality", "Management", "Revenue Resilience", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Recurring Revenue Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["gambling"],
    path: copyPasteResearchPromptPath("gambling.yaml"),
    description: "Manual Web UI copy/paste research prompt for Gambling.",
  },
  {
    id: "copy-paste-research-gaming-interactive",
    label: "Gaming Interactive Prompt",
    family: "Prompt / Technology",
    kind: "copy_paste_prompt",
    category: "technology",
    companyTypes: ["gaming_interactive"],
    scoringFactors: {
      quality: ["Franchise/IP Strength", "Retention & Live Ops", "Management", "Monetisation Quality", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Bookings vs Growth", "Cash Conversion", "Release Slate Optionality", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["gaming_interactive"],
    path: copyPasteResearchPromptPath("gaming_interactive.yaml"),
    description: "Manual Web UI copy/paste research prompt for Gaming Interactive.",
  },
  {
    id: "copy-paste-research-general-equity",
    label: "General Equity Prompt",
    family: "Prompt / General",
    kind: "copy_paste_prompt",
    category: "general",
    companyTypes: ["general_equity"],
    scoringFactors: {
      quality: ["Market Position", "Operating Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Cash-Flow Yield", "Relative Multiple", "Growth Quality", "Strategic Value"],
    },
    assetClasses: ["GENERAL"],
    templateIds: ["general_equity"],
    path: copyPasteResearchPromptPath("general_equity.yaml"),
    description: "Manual Web UI copy/paste research prompt for General Equity.",
  },
  {
    id: "copy-paste-research-gold-miner",
    label: "Gold Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["gold_miner", "polymetallic_gold_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource oz", "Exploration Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["gold_miner"],
    path: copyPasteResearchPromptPath("gold_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Gold Miner.",
  },
  {
    id: "copy-paste-research-healthcare-services",
    label: "Healthcare Services Prompt",
    family: "Prompt / Healthcare",
    kind: "copy_paste_prompt",
    category: "healthcare",
    companyTypes: ["healthcare_services"],
    scoringFactors: {
      quality: ["Demand Inelasticity", "Reimbursement/Contract Quality", "Management", "Operating Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Utilization Upside", "Strategic Value"],
    },
    assetClasses: ["HEALTHCARE"],
    templateIds: ["healthcare_services"],
    path: copyPasteResearchPromptPath("healthcare_services.yaml"),
    description: "Manual Web UI copy/paste research prompt for Healthcare Services.",
  },
  {
    id: "copy-paste-research-industrials",
    label: "Industrials Prompt",
    family: "Prompt / Equity",
    kind: "copy_paste_prompt",
    category: "equity",
    companyTypes: ["industrials"],
    scoringFactors: {
      quality: ["Demand Resilience", "Asset/Operating Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["industrials"],
    path: copyPasteResearchPromptPath("industrials.yaml"),
    description: "Manual Web UI copy/paste research prompt for Industrials.",
  },
  {
    id: "copy-paste-research-industrials-consumer-reit",
    label: "Industrials / Consumer / REIT Prompt",
    family: "Prompt / Equity",
    kind: "copy_paste_prompt",
    category: "equity",
    companyTypes: ["industrials", "consumer_retail", "real_estate_reit"],
    scoringFactors: {
      quality: ["Demand Resilience", "Asset/Operating Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Earnings/FCF Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["industrials_consumer_reit"],
    path: copyPasteResearchPromptPath("industrials_consumer_reit.yaml"),
    description: "Manual Web UI copy/paste research prompt for Industrials / Consumer / REIT.",
  },
  {
    id: "copy-paste-research-insurance",
    label: "Insurance Prompt",
    family: "Prompt / Financials",
    kind: "copy_paste_prompt",
    category: "financials",
    companyTypes: ["insurance"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Underwriting Quality", "Management", "Reserve Adequacy", "Capital & Liquidity", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "P/B vs ROE", "Earnings Power vs Price", "Capital Return Capacity", "Strategic Value"],
    },
    assetClasses: ["FINANCIALS"],
    templateIds: ["insurance"],
    path: copyPasteResearchPromptPath("insurance.yaml"),
    description: "Manual Web UI copy/paste research prompt for Insurance.",
  },
  {
    id: "copy-paste-research-iron-ore-miner",
    label: "Iron Ore Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["iron_ore_miner"],
    scoringFactors: {
      quality: ["Jurisdiction/Infrastructure", "Resource/Reserve Quality", "Cost Curve Position", "Management", "Funding/Balance Sheet", "ESG/Permitting"],
      value: ["NAV vs Market Cap", "EV/Reserve or Resource Tonne", "Cost Competitiveness", "Expansion Optionality", "Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["iron_ore_miner"],
    path: copyPasteResearchPromptPath("iron_ore_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Iron Ore Miner.",
  },
  {
    id: "copy-paste-research-lithium-miner",
    label: "Lithium Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["lithium_miner", "polymetallic_lithium_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource t LCE", "Expansion Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["lithium_miner"],
    path: copyPasteResearchPromptPath("lithium_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Lithium Miner.",
  },
  {
    id: "copy-paste-research-mining-services",
    label: "Mining Services Prompt",
    family: "Prompt / Industrials",
    kind: "copy_paste_prompt",
    category: "industrials",
    companyTypes: ["mining_services"],
    scoringFactors: {
      quality: ["Revenue Visibility", "Contract Quality", "Utilisation and Execution", "Cash Conversion", "Balance Sheet", "Customer and Commodity Diversification"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Cycle and Peers", "FCF Yield", "Fleet/Asset Replacement Value", "Strategic Value"],
    },
    assetClasses: ["MINING_SERVICES", "INDUSTRIALS", "MATERIALS"],
    templateIds: ["mining_services"],
    path: copyPasteResearchPromptPath("mining_services.yaml"),
    description: "Manual Web UI copy/paste research prompt for Mining Services.",
  },
  {
    id: "copy-paste-research-media-publishing",
    label: "Media & Publishing Prompt",
    family: "Prompt / Media",
    kind: "copy_paste_prompt",
    category: "media",
    companyTypes: ["media_publishing"],
    scoringFactors: {
      quality: ["Audience/Brand Quality", "Revenue Mix Durability", "Cost Discipline", "Digital Transition", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Subscriber/Audience Value", "Strategic Value"],
    },
    assetClasses: ["MEDIA"],
    templateIds: ["media_publishing"],
    path: copyPasteResearchPromptPath("media_publishing.yaml"),
    description: "Manual Web UI copy/paste research prompt for Media & Publishing.",
  },
  {
    id: "copy-paste-research-medtech",
    label: "Medtech Prompt",
    family: "Prompt / Healthcare",
    kind: "copy_paste_prompt",
    category: "healthcare",
    companyTypes: ["medtech"],
    scoringFactors: {
      quality: ["Regulatory & Quality Systems", "Clinical/Technical Evidence", "Management", "Commercial Execution", "Cash Runway/Funding", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Sales vs Growth", "Gross Margin & Cash Conversion", "Adoption Curve Optionality", "Strategic Value"],
    },
    assetClasses: ["HEALTHCARE"],
    templateIds: ["medtech"],
    path: copyPasteResearchPromptPath("medtech.yaml"),
    description: "Manual Web UI copy/paste research prompt for Medtech.",
  },
  {
    id: "copy-paste-research-pharma-biotech",
    label: "Pharmaceutical & Biotech Prompt",
    family: "Prompt / Pharma",
    kind: "copy_paste_prompt",
    category: "pharma",
    companyTypes: ["pharma_biotech", "medtech"],
    scoringFactors: {
      quality: ["Regulatory Environment", "Scientific & Manufacturing Capability", "Management", "Pipeline Maturity", "Cash Runway/Funding", "Clinical & Ethical Standards"],
      value: ["rNPV vs Market Cap", "EV / Risk-Adjusted Peak Sales", "Pipeline Optionality", "Competitive Position", "Strategic Value"],
    },
    assetClasses: ["PHARMA"],
    templateIds: ["pharma_biotech"],
    path: copyPasteResearchPromptPath("pharma_biotech.yaml"),
    description: "Manual Web UI copy/paste research prompt for Pharmaceutical & Biotech.",
  },
  {
    id: "copy-paste-research-rare-earths-critical-minerals",
    label: "Rare Earths & Critical Minerals Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["rare_earths_critical_minerals"],
    scoringFactors: {
      quality: ["Resource/Processing Quality", "Strategic Supply Chain Position", "Permitting/Jurisdiction", "Management", "Funding/Balance Sheet", "ESG"],
      value: ["Risked NAV vs Market Cap", "EV/Resource Unit", "Separation/Processing Optionality", "Strategic/Policy Value", "Offtake/Funding Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["rare_earths_critical_minerals"],
    path: copyPasteResearchPromptPath("rare_earths_critical_minerals.yaml"),
    description: "Manual Web UI copy/paste research prompt for Rare Earths & Critical Minerals.",
  },
  {
    id: "copy-paste-research-real-estate-reit",
    label: "Real Estate / REIT Prompt",
    family: "Prompt / Equity",
    kind: "copy_paste_prompt",
    category: "equity",
    companyTypes: ["real_estate_reit"],
    scoringFactors: {
      quality: ["Asset Quality", "Occupancy & Lease Quality", "Management", "Execution", "Balance Sheet", "Governance"],
      value: ["NAV vs Market Cap", "FFO/AFFO Yield", "Multiple vs Peers", "Growth/Reinvestment Quality", "Strategic Value"],
    },
    assetClasses: ["EQUITY"],
    templateIds: ["real_estate_reit"],
    path: copyPasteResearchPromptPath("real_estate_reit.yaml"),
    description: "Manual Web UI copy/paste research prompt for Real Estate / REIT.",
  },
  {
    id: "copy-paste-research-semiconductors",
    label: "Semiconductors Prompt",
    family: "Prompt / Technology",
    kind: "copy_paste_prompt",
    category: "technology",
    companyTypes: ["semiconductors"],
    scoringFactors: {
      quality: ["Technology/IP Position", "End-Market Quality", "Management", "Cycle Execution", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "Cycle-Normal Earnings Power", "Multiple vs Peers", "Margin Resilience", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["semiconductors"],
    path: copyPasteResearchPromptPath("semiconductors.yaml"),
    description: "Manual Web UI copy/paste research prompt for Semiconductors.",
  },
  {
    id: "copy-paste-research-silver-miner",
    label: "Silver Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["silver_miner", "polymetallic_silver_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource oz", "Exploration Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["silver_miner"],
    path: copyPasteResearchPromptPath("silver_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Silver Miner.",
  },
  {
    id: "copy-paste-research-software-saas",
    label: "Software & SaaS Prompt",
    family: "Prompt / Technology",
    kind: "copy_paste_prompt",
    category: "technology",
    companyTypes: ["software_saas"],
    scoringFactors: {
      quality: ["Market & Demand Quality", "Product Moat", "Management", "Growth Quality", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Sales vs Growth", "Rule of 40 & Margin Path", "Retention Economics", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["software_saas"],
    path: copyPasteResearchPromptPath("software_saas.yaml"),
    description: "Manual Web UI copy/paste research prompt for Software & SaaS.",
  },
  {
    id: "copy-paste-research-steel-base-metals-processing",
    label: "Steel & Base Metals Processing Prompt",
    family: "Prompt / Materials",
    kind: "copy_paste_prompt",
    category: "materials",
    companyTypes: ["steel_base_metals_processing"],
    scoringFactors: {
      quality: ["Cost Curve Position", "Asset/Plant Quality", "End-Market Exposure", "Cash Conversion", "Balance Sheet", "Governance"],
      value: ["Cycle-Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Replacement/Asset Value", "Strategic Value"],
    },
    assetClasses: ["MATERIALS"],
    templateIds: ["steel_base_metals_processing"],
    path: copyPasteResearchPromptPath("steel_base_metals_processing.yaml"),
    description: "Manual Web UI copy/paste research prompt for Steel & Base Metals Processing.",
  },
  {
    id: "copy-paste-research-technology-platforms",
    label: "Technology Platforms Prompt",
    family: "Prompt / Technology",
    kind: "copy_paste_prompt",
    category: "technology",
    companyTypes: ["technology_platforms"],
    scoringFactors: {
      quality: ["Platform/Product Moat", "Retention & Network Effects", "Management", "Growth Quality", "Balance Sheet", "Governance"],
      value: ["Intrinsic Value vs Market Cap", "EV/Sales vs Growth", "Margin Path", "Unit Economics", "Strategic Value"],
    },
    assetClasses: ["TECHNOLOGY"],
    templateIds: ["technology_platforms"],
    path: copyPasteResearchPromptPath("technology_platforms.yaml"),
    description: "Manual Web UI copy/paste research prompt for Technology Platforms.",
  },
  {
    id: "copy-paste-research-telecommunications",
    label: "Telecommunications Prompt",
    family: "Prompt / Telecommunications",
    kind: "copy_paste_prompt",
    category: "telecommunications",
    companyTypes: ["telecommunications"],
    scoringFactors: {
      quality: ["Network Quality", "Subscriber Economics", "Pricing Power", "Capital Intensity", "Balance Sheet", "Governance"],
      value: ["DCF/FCF vs Market Cap", "EV/EBITDA vs Peers", "Dividend Capacity", "Infrastructure Optionality", "Strategic Value"],
    },
    assetClasses: ["TELECOMMUNICATIONS"],
    templateIds: ["telecommunications"],
    path: copyPasteResearchPromptPath("telecommunications.yaml"),
    description: "Manual Web UI copy/paste research prompt for Telecommunications.",
  },
  {
    id: "copy-paste-research-transport-logistics",
    label: "Transport & Logistics Prompt",
    family: "Prompt / Industrials",
    kind: "copy_paste_prompt",
    category: "industrials",
    companyTypes: ["transport_logistics"],
    scoringFactors: {
      quality: ["Route/Network Quality", "Cycle Resilience", "Cost Control", "Asset Utilization", "Balance Sheet", "Governance"],
      value: ["Normalized Earnings vs Market Cap", "EV/EBITDA vs Peers", "FCF Yield", "Asset/Network Value", "Strategic Value"],
    },
    assetClasses: ["INDUSTRIALS"],
    templateIds: ["transport_logistics"],
    path: copyPasteResearchPromptPath("transport_logistics.yaml"),
    description: "Manual Web UI copy/paste research prompt for Transport & Logistics.",
  },
  {
    id: "copy-paste-research-uranium-miner",
    label: "Uranium Miner Prompt",
    family: "Prompt / Resources",
    kind: "copy_paste_prompt",
    category: "resources",
    companyTypes: ["uranium_miner", "polymetallic_uranium_miner"],
    scoringFactors: {
      quality: ["Jurisdiction", "Infrastructure", "Management", "Development Stage", "Funding", "ESG"],
      value: ["NPV vs Market Cap", "EV/Resource lb U3O8", "Exploration Upside", "Cost Competitiveness", "M&A Strategic Value"],
    },
    assetClasses: ["RESOURCES"],
    templateIds: ["uranium_miner"],
    path: copyPasteResearchPromptPath("uranium_miner.yaml"),
    description: "Manual Web UI copy/paste research prompt for Uranium Miner.",
  },
  {
    id: "copy-paste-research-utilities",
    label: "Utilities Prompt",
    family: "Prompt / Utilities",
    kind: "copy_paste_prompt",
    category: "utilities",
    companyTypes: ["utilities"],
    scoringFactors: {
      quality: ["Regulatory Framework", "Asset Base Quality", "Earnings Resilience", "Capital Structure", "Execution", "Governance"],
      value: ["Regulated Asset Value vs Market Cap", "Dividend/FCF Support", "Allowed Return vs WACC", "Growth Capex Quality", "Strategic Infrastructure Value"],
    },
    assetClasses: ["UTILITIES"],
    templateIds: ["utilities"],
    path: copyPasteResearchPromptPath("utilities.yaml"),
    description: "Manual Web UI copy/paste research prompt for Utilities.",
  },
];


export const ENRICHMENT_TEMPLATES: EnrichmentTemplate[] = [
  ...RETRIEVAL_ENRICHMENT_TEMPLATES,
  ...COPY_PASTE_RESEARCH_PROMPT_TEMPLATES,
];

export const DEFAULT_ENRICHMENT_TEMPLATE_ID = "retrieval-gold-miner";
